name = "images"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[[rules]]
globs = ["**/*.png"]
type = "Data"

[env.current]
route = { pattern = "images.rollup.id", custom_domain = true, zone_name = "rollup.id" }

[env.current.vars]
UPLOAD_WINDOW_SECONDS = 200
HASH_INTERNAL_CLOUDFLARE_ACCOUNT_ID = "VqQy1abBMHYDZwVsTbsSMw"
