name = "ping"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true

durable_objects.bindings = [
  { name = "REPLY_MESSAGE", class_name = "ReplyMessage" }
]
services = [
]

[dev]
port = 51337
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "REPLY_MESSAGE", class_name = "ReplyMessage" }
]
services = [
]

[env.next]
durable_objects.bindings = [
  { name = "REPLY_MESSAGE", class_name = "ReplyMessage" }
]
services = [
]

[env.current]
durable_objects.bindings = [
  { name = "REPLY_MESSAGE", class_name = "ReplyMessage" }
]
services = [
]

[[migrations]]
tag = "v0"
new_classes = ["ReplyMessage"]
