# cfw/starbase/wrangler.toml
name = "starbase"
main = "src/index.ts"
compatibility_date = "2022-09-14"

# A list of other Clouflare services bound to this service.
# services = [
#   { binding = "RELAY", service = "kubelt-svc-relay", environment = "production" },
# ]

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# - DATADOG_TOKEN
[vars]
USER_NAME = "Robert"

[durable_objects]
bindings = [
  { name = "STARBASE_APP", class_name = "StarbaseApp" },
]

[[migrations]]
tag = "v1"
new_classes = ["StarbaseApp"]
