# nftar/cloudbuild.yaml
---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nftar/api',
      '.'
    ]

images:
  - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/nftar/api'
