name = "analytics"
main = "src/index.ts"
compatibility_date = "2023-05-18"
workers_dev = false
node_compat = true

routes = [{ pattern = "analytics.rollup.id", custom_domain = true }]

[dev]
port = 20210
inspector_port = 21210
local_protocol = "http"
