name = "starbase"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true


# #############################################################################
# NB: we don't supply an external route for this service as it is
# intended to be service-bound.
# #############################################################################

# Don't automatically expose this service at:
# <worker-name>.<account-name>.workers.dev.
workers_dev = false

# Services
# -----------------------------------------------------------------------------
# A list of other Clouflare services bound to this service.

services = [
  { binding = "Edges", service = "edges" }
]

# Durable Objects
# -----------------------------------------------------------------------------

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
]

# KV
# -----------------------------------------------------------------------------

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" },
  { binding = "LOOKUP", id = "27035c39f40343a4a0deab740f2b9fcc", preview_id = "883765b4372d42bea90c67e2e6bfb64b" }
]

# Secrets
# -----------------------------------------------------------------------------

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# N/A

[vars]
ENVIRONMENT = "local"

# Dev
# -----------------------------------------------------------------------------

[dev]
port = 9090
local_protocol = "http"

[[migrations]]
tag = "v2"
# new_classes = [
#   "StarbaseApplication",
# ]
# renamed_classes = [
#   { from = "OldName", to = "NewName" }
# ]
deleted_classes = [
  "StarbaseContract",
  "StarbaseUser",
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "StarbaseAnalytics"  },
]

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]

services = [
  { binding = "Edges", service = "edges-dev" }
]

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "StarbaseAnalyticsDev"  },
]

[env.dev.vars]
ENVIRONMENT = "dev"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
  { binding = "Edges", service = "edges-next" }
]

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "StarbaseAnalyticsNext"  },
]

[env.next.vars]
ENVIRONMENT = "next"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

services = [
  { binding = "Edges", service = "edges-current" }
]

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "StarbaseAnalyticsCurrent"  },
]

[env.current.vars]
ENVIRONMENT = "current"
