name = "starbase"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true


# #############################################################################
# NB: we don't supply an external route for this service as it is
# intended to be service-bound.
# #############################################################################

# Don't automatically expose this service at:
# <worker-name>.<account-name>.workers.dev.
workers_dev = false

# Services
# -----------------------------------------------------------------------------
# A list of other Clouflare services bound to this service.

services = [
]

# Durable Objects
# -----------------------------------------------------------------------------

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
  { name = "StarbaesContract", class_name = "StarbaseContract" },
  { name = "StarbaseUser", class_name = "StarbaseUser" },
]

# KV
# -----------------------------------------------------------------------------

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" },
  { binding = "LOOKUP", id = "27035c39f40343a4a0deab740f2b9fcc", preview_id = "883765b4372d42bea90c67e2e6bfb64b" }
]

# Secrets
# -----------------------------------------------------------------------------

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# N/A

[vars]
ENVIRONMENT = "local"

# Dev
# -----------------------------------------------------------------------------

[dev]
port = 9090
local_protocol = "http"

[[migrations]]
tag = "v1"
new_classes = [
  "StarbaseApplication",
  "StarbaseContract",
  "StarbaseUser",
]
# renamed_classes = [
#   { from = "OldName", to = "NewName" }
# ]
# deleted_classes = [
#   "DeprecatedClass"
# ]

# KV
# -----------------------------------------------------------------------------
# We use a KV store to contain application core fixture data for
# platform applications. When an "init" RPC call is made to the service
# this fixture data is retrieved and a core is created for each
# application.
#
# The key at which each fixture object is stored looks like:
#   ${env-name}-${app-name}
# E.g.
#   dev-appname
#   next-appname
#   current/appname
#
# $ npx wrangler kv:key put dev-console --path <fixture.json> --namespace-id <preview_id>
#
# NB: Each key is deleted after initialization has completed.

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]

services = [
]

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
]

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" },
  { binding = "LOOKUP", id = "27035c39f40343a4a0deab740f2b9fcc", preview_id = "883765b4372d42bea90c67e2e6bfb64b" }
]

[env.dev.vars]
ENVIRONMENT = "dev"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
]

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" },
  { binding = "LOOKUP", id = "27035c39f40343a4a0deab740f2b9fcc", preview_id = "883765b4372d42bea90c67e2e6bfb64b" }
]

[env.next.vars]
ENVIRONMENT = "next"
PLATFORM_OWNER = "@kubelt"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

durable_objects.bindings = [
  { name = "StarbaseApp", class_name = "StarbaseApplication" },
]

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" },
  { binding = "LOOKUP", id = "27035c39f40343a4a0deab740f2b9fcc", preview_id = "883765b4372d42bea90c67e2e6bfb64b" }
]

[env.current.vars]
ENVIRONMENT = "current"
