# cfw/starbase/wrangler.toml
name = "starbase"
main = "src/index.ts"
compatibility_date = "2022-09-14"

# #############################################################################
# NB: we don't supply an external route for this service as it is
# intended to be service-bound.
# #############################################################################

# Don't automatically expose this service at:
# <worker-name>.<account-name>.workers.dev.
workers_dev = false

# Services
# -----------------------------------------------------------------------------
# A list of other Clouflare services bound to this service.

services = [
  { binding = "Account", service = "account" }
]

# Secrets
# -----------------------------------------------------------------------------

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# N/A

# Durable Objects
# -----------------------------------------------------------------------------

[dev]

[[migrations]]
tag = "v1"
new_classes = [
  "StarbaseApplication",
  "StarbaseContract",
  "StarbaseUser",
]

# KV
# -----------------------------------------------------------------------------
# We use a KV store to contain application core fixture data for
# platform applications. When an "init" RPC call is made to the service
# this fixture data is retrieved and a core is created for each
# application.
#
# The key at which each fixture object is stored looks like:
#   ${env-name}-${app-name}
# E.g.
#   dev-appname
#   next-appname
#   current/appname
#
# $ npx wrangler kv:key put dev-console --path <fixture.json> --namespace-id <preview_id>
#
# NB: Each key is deleted after initialization has completed.

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]

services = [
  { binding = "Account", service = "account-dev", environment = "production" }
]

durable_objects.bindings = [
  { name = "STARBASE_APP", class_name = "StarbaseApplication" },
  { name = "STARBASE_CONTRACT", class_name = "StarbaseContract" },
  { name = "STARBASE_USER", class_name = "StarbaseUser" },
]

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" }
]

[env.dev.vars]
ENVIRONMENT = "dev"
PLATFORM_OWNER = "@kubelt"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
  { binding = "Account", service = "account-next", environment = "production" }
]

durable_objects.bindings = [
  { name = "STARBASE_APP", class_name = "StarbaseApplication" },
  { name = "STARBASE_CONTRACT", class_name = "StarbaseContract" },
  { name = "STARBASE_USER", class_name = "StarbaseUser" },
]

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" }
]

[env.next.vars]
ENVIRONMENT = "next"
PLATFORM_OWNER = "@kubelt"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

services = [
  { binding = "Account", service = "account-current", environment = "production" }
]

durable_objects.bindings = [
  { name = "STARBASE_APP", class_name = "StarbaseApplication" },
  { name = "STARBASE_CONTRACT", class_name = "StarbaseContract" },
  { name = "STARBASE_USER", class_name = "StarbaseUser" },
]

kv_namespaces = [
  { binding = "FIXTURES", id = "29bcce9f29d9499688da216bcc3dbb49", preview_id = "afbd7707df58426c9926a483c979b9a5" }
]

[env.current.vars]
ENVIRONMENT = "current"
PLATFORM_OWNER = "@kubelt"
