name = "galaxy"
main = "src/index.ts"
compatibility_date = "2022-10-19"
node_compat = true

[dev]
port = 8787
local_protocol = "http"

[env.dev]
services = [
  { binding = "OORT", service = "oort-dev"}
]

[env.next]
services = [
  { binding = "OORT", service = "oort-testnet"}
]

[env.current]
services = [
  { binding = "OORT", service = "oort-mainnet"}
]
