# Note that Webflow manages the public-facing /docs routes for threeid.xyz and kubelt.com.
root: ./docs/

structure:
  readme: 3id.md
  summary: CONTENTS.md

# redirects:
#  previous/page: new-folder/page.md
