defaultSemverRangePrefix: ''

nodeLinker: node-modules

# nmHoistingLimits: workspaces

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.4.cjs

npmScopes:
  teambit:
    npmRegistryServer: https://node.bit.cloud
  kubelt-ui:
    npmRegistryServer: https://node.bit.cloud
