defaultSemverRangePrefix: ""

nodeLinker: node-modules

# - "workspaces": don't hoist packages past workspace that depends on them
# - "dependencies": packages aren't hoisted past the direct dependencies for each workspace
# - "none": [default] packages are hoisted as much as possible
# nmHoistingLimits: workspaces

npmScopes:
  kubelt-ui:
    npmRegistryServer: "https://node.bit.cloud"
  teambit:
    npmRegistryServer: "https://node.bit.cloud"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
