name = "object"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true

durable_objects.bindings = [
  { name = "Meta", class_name = "Meta" }
]
r2_buckets = [
  { binding = "Bucket", bucket_name = "threeid-dev", preview_bucket_name = "threeid-dev" },
]

[dev]
port = 9595
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Meta", class_name = "Meta" }
]
r2_buckets = [
  { binding = "Bucket", bucket_name = "threeid-dev", preview_bucket_name = "threeid-dev" },
]

[env.next]
durable_objects.bindings = [
  { name = "Meta", class_name = "Meta" }
]
r2_buckets = [
  { binding = "Bucket", bucket_name = "threeid-next", preview_bucket_name = "threeid-next" },
]

[env.current]
durable_objects.bindings = [
  { name = "Meta", class_name = "Meta" }
]
r2_buckets = [
  { binding = "Bucket", bucket_name = "threeid-current", preview_bucket_name = "threeid-current" },
]

[[migrations]]
tag = "v0"
new_classes = ["Meta"]
