name = "galaxy"
main = "src/index.ts"
compatibility_date = "2022-10-19"
logpush = true
node_compat = true
wrangler_dev = false

services = [
  { binding = "Core", service = "core" },
]

[dev]
port = 10401
inspector_port = 11401
local_protocol = "http"
