name = "galaxy"
main = "src/index.ts"
compatibility_date = "2022-10-19"
node_compat = true
wrangler_dev = false

# Services binding for local development
services = [
  { binding = "Account", service = "account" },
  { binding = "Address", service = "address" },
  { binding = "Starbase", service = "starbase"},
]

[dev]
port = 8787
local_protocol = "http"

[vars]
ALCHEMY_ETH_NETWORK="goerli"
ALCHEMY_POLYGON_NETWORK="mumbai"

[env.dev]
route = { pattern = "galaxy-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
services = [
  { binding = "Account", service = "account-dev" },
  { binding = "Address", service = "address-dev" },
  { binding = "Starbase", service = "starbase-dev" },
  { binding = "Indexer, service = "indexer-dev" },
]

[env.dev.vars]
ALCHEMY_ETH_NETWORK="goerli"
ALCHEMY_POLYGON_NETWORK="mumbai"

[env.next]
route = { pattern = "galaxy-next.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
services = [
  { binding = "Account", service = "account-next" },
  { binding = "Address", service = "address-next" },
  { binding = "Starbase", service = "starbase-next" },
  { binding = "Indexer, service = "indexer-next" },
]

[env.next.vars]
ALCHEMY_ETH_NETWORK="goerli"
ALCHEMY_POLYGON_NETWORK="mumbai"

[env.current]
route = { pattern = "galaxy.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
services = [
  { binding = "Account", service = "account-current" },
  { binding = "Address", service = "address-current" },
  { binding = "Starbase", service = "starbase-current" },
  { binding = "Indexer, service = "indexer-current" },
]

[env.current.vars]
ALCHEMY_ETH_NETWORK="mainnet"
ALCHEMY_POLYGON_NETWORK="mainnet"


