name = "galaxy"
main = "src/index.ts"
# NEED TO ADD ACCOUNT ID TO TEST REMOTE LOCALLY
compatibility_date = "2022-10-19"
node_compat = true
wrangler_dev = false
logpush = true

# Services binding for local development
services = [
  { binding = "Account", service = "account" },
  { binding = "Access", service = "access" },
  { binding = "Address", service = "address" },
  { binding = "Starbase", service = "starbase" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[vars]
JWKS_INTERNAL_URL_BASE = 'http://localhost:10001/.well-known/jwks.json'

[dev]
port = 10401
inspector_port = 11401
local_protocol = "http"

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.dev.vars]
JWKS_INTERNAL_URL_BASE = "https://passport-dev.pz3r0.com/.well-known/jwks.json"

[env.dev]
route = { pattern = "galaxy-dev.rollup.id", custom_domain = true, zone_name = "rollup.id" }
services = [
  { binding = "Account", service = "account-dev" },
  { binding = "Access", service = "access-dev" },
  { binding = "Address", service = "address-dev" },
  { binding = "Starbase", service = "starbase-dev" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.next.vars]
JWKS_INTERNAL_URL_BASE = "https://passport-next.pz3r0.com/.well-known/jwks.json"

[env.next]
route = { pattern = "galaxy-next.rollup.id", custom_domain = true, zone_name = "rollup.id" }
services = [
  { binding = "Account", service = "account-next" },
  { binding = "Address", service = "address-next" },
  { binding = "Access", service = "access-next" },
  { binding = "Starbase", service = "starbase-next" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.current.vars]
JWKS_INTERNAL_URL_BASE = "https://passport.pz3r0.com/.well-known/jwks.json"

[env.current]
route = { pattern = "galaxy.rollup.id", custom_domain = true, zone_name = "rollup.id" }
services = [
  { binding = "Account", service = "account-current" },
  { binding = "Address", service = "address-current" },
  { binding = "Access", service = "access-current" },
  { binding = "Starbase", service = "starbase-current" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]
