name = "galaxy"
main = "src/index.ts"
compatibility_date = "2022-10-19"
node_compat = true

# Services binding for local development
services = [
  { binding = "Oort", service = "oort"},
  { binding = "Account", service = "account" },
  { binding = "Address", service = "address" },
  { binding = "Icons", service = "icons" },
]

[dev]
port = 8787
local_protocol = "http"

[env.dev]
route = { pattern = "galaxy-dev.kubelt.com", custom_domain = true, zone_name = "kubelt.com" }
services = [
  { binding = "Oort", service = "oort-devnet"},
  { binding = "Account", service = "account" },
  { binding = "Address", service = "address" },
  { binding = "Icons", service = "icons" },
]

[env.next]
route = { pattern = "galaxy-next.kubelt.com", custom_domain = true, zone_name = "kubelt.com" }
services = [
  { binding = "Oort", service = "oort-testnet"},
  { binding = "Account", service = "account" },
  { binding = "Address", service = "address" },
  { binding = "Icons", service = "icons" },
]

[env.current]
route = { pattern = "galaxy.kubelt.com", custom_domain = true, zone_name = "kubelt.com" }
services = [
  { binding = "Oort", service = "oort-mainnet"},
  { binding = "Account", service = "account" },
  { binding = "Address", service = "address" },
  { binding = "Icons", service = "icons" },
]


