# cfw/icons/wrangler.toml

name = "icons"
main = "src/index.ts"
compatibility_date = "2022-10-05"

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# - AUTH_EMAIL
# - AUTH_KEY
[vars]
# The account ID that owns uploaded images.
ACCOUNT_ID = "2906425795180ede5ac707178f96406d"
# The duration in seconds that returned upload URL is good for.
# - minimum: 2 minutes
# - maximum: 6 hours
UPLOAD_WINDOW_SECONDS = 15
