name = "address"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false
logpush = true

durable_objects.bindings = [{ name = "Address", class_name = "Address" }]

services = [
  { binding = "Edges", service = "edges" },
  { binding = "Images", service = "images" },
  { binding = "Email", service = "email" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[vars]
PASSPORT_URL = "http://localhost:10001"
MINTPFP_CONTRACT_ADDRESS = "0x028aE75Bb01eef2A581172607b93af8D24F50643"
TTL_IN_MS = 25_000
MAX_ATTEMPTS = 5
DELAY_BETWEEN_REGENERATION_ATTEMPTS_IN_MS = 2_000
REGENERATION_COOLDOWN_PERIOD_IN_MS = 30_000
MAX_ATTEMPTS_TIME_PERIOD_IN_MS = 300_000

[dev]
port = 10102
inspector_port = 11102
local_protocol = "http"

[[migrations]]
tag = "v0"
new_classes = ["Core"]

[[migrations]]
tag = "v1"
new_classes = ["CryptoCore"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "CryptoCore", to = "CryptoAddress" }]
deleted_classes = ["Core"]

[[migrations]]
tag = "v3"
new_classes = ["OAuthAddress"]

[[migrations]]
tag = "v4"
deleted_classes = ["CryptoAddress"]
new_classes = ["Address"]

[env.dev]
durable_objects.bindings = [{ name = "Address", class_name = "Address" }]
services = [
  { binding = "Edges", service = "edges-dev" },
  { binding = "Images", service = "images-dev" },
  { binding = "Email", service = "email-dev" },
]
kv_namespaces = [
  { binding = "HANDLES", id = "fca42f2091f14eebb9226513ed8a4c09" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.dev.vars]
PASSPORT_URL = "https://passport-dev.rollup.id"
MINTPFP_CONTRACT_ADDRESS = "0x028aE75Bb01eef2A581172607b93af8D24F50643"
TTL_IN_MS = 25_000
MAX_ATTEMPTS = 5
DELAY_BETWEEN_REGENERATION_ATTEMPTS_IN_MS = 2_000
REGENERATION_COOLDOWN_PERIOD_IN_MS = 30_000
MAX_ATTEMPTS_TIME_PERIOD_IN_MS = 300_000

[env.next]
durable_objects.bindings = [{ name = "Address", class_name = "Address" }]
services = [
  { binding = "Edges", service = "edges-next" },
  { binding = "Images", service = "images-next" },
  { binding = "Email", service = "email-next" },

]
kv_namespaces = [
  { binding = "HANDLES", id = "814a8ca024cd4fda8a667a4143cb4825" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.next.vars]
PASSPORT_URL = "https://passport-next.rollup.id"
MINTPFP_CONTRACT_ADDRESS = "0x028aE75Bb01eef2A581172607b93af8D24F50643"
TTL_IN_MS = 300_000
MAX_ATTEMPTS = 5
DELAY_BETWEEN_REGENERATION_ATTEMPTS_IN_MS = 30_000
REGENERATION_COOLDOWN_PERIOD_IN_MS = 600_000
MAX_ATTEMPTS_TIME_PERIOD_IN_MS = 300_000

[env.current]
durable_objects.bindings = [{ name = "Address", class_name = "Address" }]
services = [
  { binding = "Edges", service = "edges-current" },
  { binding = "Images", service = "images-current" },
  { binding = "Email", service = "email-current" },
]
kv_namespaces = [
  { binding = "HANDLES", id = "d7d0ac60a79f4848bf8372b01a487888" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.current.vars]
PASSPORT_URL = "https://passport.rollup.id"
MINTPFP_CONTRACT_ADDRESS = "0x3ebfaFE60F3Ac34f476B2f696Fc2779ff1B03193"
TTL_IN_MS = 300_000
MAX_ATTEMPTS = 5
DELAY_BETWEEN_REGENERATION_ATTEMPTS_IN_MS = 30_000
REGENERATION_COOLDOWN_PERIOD_IN_MS = 600_000
MAX_ATTEMPTS_TIME_PERIOD_IN_MS = 300_000
