name = "address"
main = "dist/index.mjs"
# type = "javascript"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

[build]
command = "node build.js"

durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]

services = [
  { binding = "Access", service = "access" },
  { binding = "Edges", service = "edges" }
]

[[ d1_databases ]]
binding = "COLLECTIONS" # i.e. available in your Worker on env.DB
database_name = "collections-dev"
database_id = "13213d87-dc22-442a-ad81-afb8139edbf4"

[[queues.producers]]
 queue = "blockchain-activity"
 binding = "BLOCKCHAIN_ACTIVITY"
 
[[queues.consumers]]
queue = "blockchain-activity"
max_batch_size = 1 # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds

[vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5
URL_MORALIS_WEBHOOK = "https://localhost:9292/webhooks/moralis"

[dev]
port = 9191
local_protocol = "http"

[[migrations]]
tag = "v0"
new_classes = ["Core"]

[[migrations]]
tag = "v1"
new_classes = ["CryptoCore"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "CryptoCore", to = "CryptoAddress" }]
deleted_classes = ["Core"]

[env.dev]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]
services = [
  { binding = "Access", service = "access-dev" },
  { binding = "Edges", service = "edges-dev" }
]
d1_databases = [
  { binding = "COLLECTIONS", database_name = "collections-dev", database_id = "13213d87-dc22-442a-ad81-afb8139edbf4" }
]

[env.dev.vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5
URL_MORALIS_WEBHOOK = "https://beacon-dev/webhooks/moralis"

[env.next]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]
services = [
  { binding = "Access", service = "access-next" },
  { binding = "Edges", service = "edges-next" }
]
d1_databases = [
  { binding = "COLLECTIONS", database_name = "collections-next", database_id = "9f4437bc-1a3f-4e4d-8c7f-19cf964d28d1" }
]

[env.next.vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5
URL_MORALIS_WEBHOOK = "https://beacon-next/webhooks/moralis"


[env.current]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]
services = [
  { binding = "Access", service = "access-current" },
  { binding = "Edges", service = "edges-current" }
]
d1_databases = [
  { binding = "COLLECTIONS", database_name = "collections-current", database_id = "e20e21e5-f1c1-4679-ad3c-65a3854bcb30" }
]

[env.current.vars]
MINTPFP_CONTRACT_ADDRESS="0x3ebfaFE60F3Ac34f476B2f696Fc2779ff1B03193"
NFTAR_URL="https://nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=1
URL_MORALIS_WEBHOOK = "https://beacon/webhooks/moralis"

