name = "address"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]

services = [
  { binding = "Access", service = "access" },
  { binding = "Edges", service = "edges" }
]

[vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5

[dev]
port = 9191
local_protocol = "http"

[[migrations]]
tag = "v0"
new_classes = ["Core"]

[[migrations]]
tag = "v1"
new_classes = ["CryptoCore"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "CryptoCore", to = "CryptoAddress" }]
deleted_classes = ["Core"]

[env.dev]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]
services = [
  { binding = "Access", service = "access-dev" },
  { binding = "Edges", service = "edges-dev" }
]

[env.dev.vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5

[env.next]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]
services = [
  { binding = "Access", service = "access-next" },
  { binding = "Edges", service = "edges-next" }
]

[env.next.vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5

[env.current]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" }
]
services = [
  { binding = "Access", service = "access-current" },
  { binding = "Edges", service = "edges-current" }
]

[env.current.vars]
MINTPFP_CONTRACT_ADDRESS="0x3ebfaFE60F3Ac34f476B2f696Fc2779ff1B03193"
NFTAR_URL="https://nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=1
