name = "address"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" },
  { name = "OAuthAddress", class_name = "OAuthAddress" },
]

services = [
  { binding = "Access", service = "access" },
  { binding = "Edges", service = "edges" }
]

[[queues.producers]]
 queue = "blockchain-activity"
 binding = "BLOCKCHAIN_ACTIVITY"

[[queues.consumers]]
queue = "blockchain-activity"
max_batch_size = 1 # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds

[vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "AddressAnalytics"  },
]

[dev]
port = 9191
local_protocol = "http"

[[migrations]]
tag = "v0"
new_classes = ["Core"]

[[migrations]]
tag = "v1"
new_classes = ["CryptoCore"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "CryptoCore", to = "CryptoAddress" }]
deleted_classes = ["Core"]

[[migrations]]
tag = "v3"
new_classes = ["OAuthAddress"]

[env.dev]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" },
  { name = "OAuthAddress", class_name = "OAuthAddress" },
]
services = [
  { binding = "Access", service = "access-dev" },
  { binding = "Edges", service = "edges-dev" }
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "AddressAnalyticsDev"  },
]

[env.dev.vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5

[env.next]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" },
  { name = "OAuthAddress", class_name = "OAuthAddress" },
]
services = [
  { binding = "Access", service = "access-next" },
  { binding = "Edges", service = "edges-next" }
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "AddressAnalyticsNext"  },
]

[env.next.vars]
MINTPFP_CONTRACT_ADDRESS="0x028aE75Bb01eef2A581172607b93af8D24F50643"
NFTAR_URL="https://test.nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=5

[env.current]
durable_objects.bindings = [
  { name = "CryptoAddress", class_name = "CryptoAddress" },
  { name = "OAuthAddress", class_name = "OAuthAddress" },
]
services = [
  { binding = "Access", service = "access-current" },
  { binding = "Edges", service = "edges-current" }
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "AddressAnalyticsCurrent"  },
]

[env.current.vars]
MINTPFP_CONTRACT_ADDRESS="0x3ebfaFE60F3Ac34f476B2f696Fc2779ff1B03193"
NFTAR_URL="https://nftar.threeid.xyz/api"
NFTAR_CHAIN_ID=1
