# This is a singleton service and doesn't require per-env configs
name = "relayprocessor"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

[env.dev]
port = 10146
inspector_port = 11146
local_protocol = "http"

services = [{ binding = "Core", service = "core-current" }]

[env.dev.vars]
INTERNAL_RELAY_DKIM_DOMAIN = "rollup.email"
INTERNAL_RELAY_DKIM_SELECTOR = "mailchannels"
