name = "email"

main = "src/index.ts"
compatibility_date = "2022-10-05"

workers_dev = false

[dev]
port = 10105
inspector_port = 11105
local_protocol = "http"

[env]
DefaultEmailFromName = "Rollup (Local) - Notification"
DefaultEmailFromUser = "noreply"

[env.dev.vars]
DefaultEmailFromName = "Rollup (Dev) - Notifcation"
DefaultEmailFromUser = 'noreply'

[env.next.vars]
DefaultEmailFromName = "Rollup (Next) - Notifcation"
DefaultEmailFromUser = 'noreply'

[env.current.vars]
DefaultEmailFromName = "Rollup - Notifcation"
DefaultEmailFromUser = 'noreply'
