name = "email"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

[env.next.vars]
NotificationFromName = "Rollup Next - Notification"
NotificationFromUser = 'noreply-next'
