name = "email"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

[env.dev.vars]
NotificationFromName = "Rollup Dev - Notification"
NotificationFromUser = 'noreply-dev'
