name = "email"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

services = [{ binding = "Test", service = "test" }]

[dev]
port = 10105
inspector_port = 11105
local_protocol = "http"

[vars]
NotificationFromName = "Rollup Local - Notification"
NotificationFromUser = "noreplylocal"
