name = "email"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

[env.current.vars]
NotificationFromName = "Rollup - Notification"
NotificationFromUser = 'noreply'
