name = "email"

main = "src/index.ts"
compatibility_date = "2022-10-05"

workers_dev = false
logpush = true

services = [{ binding = "Test", service = "test" }]

[dev]
port = 10105
inspector_port = 11105
local_protocol = "http"

[vars]
NotificationFromName = "Rollup Local - Notification"
NotificationFromUser = "noreplylocal"

[env.dev.vars]
NotificationFromName = "Rollup Dev - Notification"
NotificationFromUser = 'noreply-dev'

[env.next.vars]
NotificationFromName = "Rollup Next - Notification"
NotificationFromUser = 'noreply-next'

[env.current.vars]
NotificationFromName = "Rollup - Notification"
NotificationFromUser = 'noreply'
