---
name: test and build
on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      crdt: ${{ steps.changes.outputs.crdt }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      # - uses: dorny/paths-filter@v2
      #   id: changes
      #   with:
      #     filters: |
      #       crdt: 'crdt/**'

  # crdt
  # ----------------------------------------------------------------------------
  build-test-crdt:
    # needs: changes
    # if: needs.changes.outputs.crdt == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('/crdt/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm install
        # working-directory: crdt
      - name: Build and Test
        run: npm test
        # working-directory: crdt
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
