# This is a singleton service and doesn't require per-env configs
name = "emailinbounder"
main = "src/index.ts"
compatibility_date = "2022-10-05"
logpush = true
workers_dev = false

[env.next]
port = 10146
inspector_port = 11146
local_protocol = "http"

services = [{ binding = "Core", service = "core-next" }]

[env.next.vars]
INTERNAL_RELAY_DKIM_DOMAIN = "rollup.email"
INTERNAL_RELAY_DKIM_SELECTOR = "mailchannels"
INTERNAL_EMAIL_DISTRIBUTION_KEY = "next"
