main = "./build/index.js"
name = "profile"
compatibility_date = "2022-04-05"
compatibility_flags = ["no_minimal_subrequests"]
workers_dev = false
logpush = true

services = [
  { binding = "Galaxy", service = "galaxy" },
  { binding = "Images", service = "images" },
]

kv_namespaces = [
  { binding = "ProfileKV", id = "ProfileKV" },
]

[build]
command = "yarn build -- --sourcemap"

[site]
bucket = "./public"

[dev]
port = 10003
inspector_port = 11003
local_protocol = "http"

[vars]
PASSPORT_URL = "http://localhost:10001"
PASSPORT_AUTH_URL = "http://localhost:10001/authorize"
PASSPORT_TOKEN_URL = "http://127.0.0.1:10001/token"
IMAGES_URL = "http://localhost/trpc"
REDIRECT_URI = "http://localhost:10003/auth/callback"
COOKIE_DOMAIN = "localhost"
TWITTER_URL = "https://twitter.com/rollupid"
DISCORD_URL = "https://discord.gg/rollupid"
MINTPFP_CONTRACT_ADDRESS = "0x028aE75Bb01eef2A581172607b93af8D24F50643"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
PROFILE_VERSION = 1
ALCHEMY_ETH_NETWORK = "mainnet"
ALCHEMY_POLYGON_NETWORK = "mainnet"
