name = "webhooks"
main = "src/index.ts"
compatibility_date = "2022-12-15"

[[queues.producers]]
 queue = "blockchain-activity"
 binding = "BLOCKCHAIN_ACTIVITY"

[dev]
port = 9292
local_protocol = "http"

[env.dev]
route = { pattern = "webhooks-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }