name = "account"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "Account", class_name = "Account" }
]
services = [
  { binding = "Edges", service = "edges" }
]

analytics_engine_datasets = [
  { binding = "AccountAnalytics", dataset = "AccountAnalytics"  },
]

[[migrations]]
tag = "v0"
new_classes = ["Core"]

[[migrations]]
tag = "v1"
renamed_classes = [{ from = "Core", to = "Account" }]

[dev]
port = 9494
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Account", class_name = "Account" }
]
services = [
  { binding = "Edges", service = "edges-dev" }
]

analytics_engine_datasets = [
  { binding = "AccountAnalytics", dataset = "AccountAnalyticsDev"  },
]

[env.next]
durable_objects.bindings = [
  { name = "Account", class_name = "Account" }
]
services = [
  { binding = "Edges", service = "edges-next" }
]

analytics_engine_datasets = [
  { binding = "AccountAnalytics", dataset = "AccountAnalyticsNext"  },
]

[env.current]
durable_objects.bindings = [
  { name = "Account", class_name = "Account" }
]
services = [
  { binding = "Edges", service = "edges-current" }
]

analytics_engine_datasets = [
  { binding = "AccountAnalytics", dataset = "AccountAnalyticsCurrent"  },
]
