name = "account"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Address", service = "address" },
  { binding = "Access", service = "access" },
]

[dev]
port = 9494
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Address", service = "address-dev" },
  { binding = "Access", service = "access-dev" },
]

[env.next]
durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Address", service = "address-next" },
  { binding = "Access", service = "access-next" },
]

[env.current]
durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Address", service = "address-current" },
  { binding = "Access", service = "access-current" },
]

[[migrations]]
tag = "v0"
new_classes = ["Core"]
