name = "account"
main = "src/index.ts"
compatibility_date = "2022-10-26"
compatibility_flags = ["no_minimal_subrequests"]
node_compat = true
workers_dev = false
logpush = true

durable_objects.bindings = [{ name = "Account", class_name = "Account" }]
services = [{ binding = "Edges", service = "edges" }]

[[migrations]]
tag = "v0"
new_classes = ["Core"]

[[migrations]]
tag = "v1"
renamed_classes = [{ from = "Core", to = "Account" }]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[vars]
JWKS_INTERNAL_URL_BASE = 'http://127.0.0.1:10001/.well-known/jwks.json'

[dev]
port = 10201
inspector_port = 11201
local_protocol = "http"

[env.dev.vars]
JWKS_INTERNAL_URL_BASE = "https://passport-dev.pz3r0.com/.well-known/jwks.json"

[env.dev]
durable_objects.bindings = [{ name = "Account", class_name = "Account" }]
services = [{ binding = "Edges", service = "edges-dev" }]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.next.vars]
JWKS_INTERNAL_URL_BASE = "https://passport-next.pz3r0.com/.well-known/jwks.json"

[env.next]
durable_objects.bindings = [{ name = "Account", class_name = "Account" }]
services = [{ binding = "Edges", service = "edges-next" }]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.current.vars]
JWKS_INTERNAL_URL_BASE = "https://passport.pz3r0.com/.well-known/jwks.json"

[env.current]
durable_objects.bindings = [{ name = "Account", class_name = "Account" }]
services = [{ binding = "Edges", service = "edges-current" }]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]
