name = "account"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Oort", service = "oort" },
]

[dev]
port = 9494
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Oort", service = "oort-dev" },
]

[env.next]
durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Oort", service = "oort-next" },
]

[env.current]
durable_objects.bindings = [
  { name = "Core", class_name = "Core" }
]
services = [
  { binding = "Oort", service = "oort-current" },
]

[[migrations]]
tag = "v0"
new_classes = ["Core"]
