name = "passport"

main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

# Services binding for local development
services = [
  { binding = "Account", service = "account"},
  { binding = "Access", service = "access"},
  { binding = "Address", service = "address"},
  { binding = "Galaxy", service = "galaxy"},
  { binding = "Starbase", service = "starbase"},
]

[site]
  bucket = "./public"

[build]
  command = "yarn build -- --sourcemap"

[dev]
port = 9696
local_protocol = "http"

[vars]
THREEID_APP_URL = "http://localhost:9797"
PASSPORT_REDIRECT_URL = "http://localhost:9696/authenticate/token"


[env.dev]
routes = [
  { pattern = "passport-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-dev"},
  { binding = "Access", service = "access-dev"},
  { binding = "Address", service = "address-dev"},
  { binding = "Galaxy", service = "galaxy-dev"},
  { binding = "Starbase", service = "starbase-dev"},
]

[env.dev.vars]
THREEID_APP_URL = "https://3id-dev.kubelt.com"
PASSPORT_REDIRECT_URL = "https://passport-dev.threeid.xyz/authenticate/token"


[env.next]
routes = [
  { pattern = "passport-next.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-next"},
  { binding = "Access", service = "access-next"},
  { binding = "Address", service = "address-next"},
  { binding = "Galaxy", service = "galaxy-next"},
  { binding = "Starbase", service = "starbase-next"},

]

[env.next.vars]
THREEID_APP_URL = "https://3id-next.kubelt.com"
PASSPORT_REDIRECT_URL = "https://passport-next.threeid.xyz/authenticate/token"

[env.next.build]
  command = "yarn build"

[env.current]
routes = [
  { pattern = "passport-current.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-current"},
  { binding = "Access", service = "access-current"},
  { binding = "Address", service = "address-current"},
  { binding = "Galaxy", service = "galaxy-current"},
  { binding = "Starbase", service = "starbase-current"},

]

[env.current.vars]
THREEID_APP_URL = "https://3id.kubelt.com"
PASSPORT_REDIRECT_URL = "https://passport.threeid.xyz/authenticate/token"

[env.current.build]
  command = "yarn build"