name = "passport"
main = "./build/index.js"
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]
node_compat = true
workers_dev = false
logpush = true

services = [
  { binding = "Core", service = "core" },
  { binding = "Images", service = "images" },
]

[build]
command = "yarn build -- --sourcemap"

[site]
bucket = "./public"

[dev]
port = 10001
inspector_port = 11001
local_protocol = "http"

[vars]
DEFAULT_HOSTS = ["localhost:10001", "127.0.0.1:10001"]
COOKIE_DOMAIN = "localhost"
PROFILE_APP_URL = "http://localhost:10003"
CONSOLE_APP_URL = "http://localhost:10002"
PASSPORT_REDIRECT_URL = "http://localhost:10001/connect/token"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/twitter/callback"
INTERNAL_MICROSOFT_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/microsoft/callback"
INTERNAL_APPLE_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/apple/callback"
INTERNAL_DISCORD_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/discord/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
WALLET_CONNECT_PROJECT_ID = "36efbf71d7586e254d72041a15a42078"
POSTHOG_API_KEY = "phc_f7q7V62YWsS0FKyIRxO36xyUMFYJ8oahurHPBAXkGe5"
POSTHOG_PROXY_HOST = "https://analytics.rollup.id"
