name = "passport"

main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

# Services binding for local development
services = [
  { binding = "Account", service = "account"},
  { binding = "Access", service = "access"},
  { binding = "Galaxy", service = "galaxy"},
]

[site]
  bucket = "./public"

[build]
  command = "yarn build -- --sourcemap"

[dev]
port = 9696
local_protocol = "http"

[env.dev]
routes = [
  { pattern = "passport-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-dev"},
  { binding = "Access", service = "access-dev"},
  { binding = "Galaxy", service = "galaxy-dev"},
]

[env.next]
routes = [
  { pattern = "passport-next.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-next"},
  { binding = "Access", service = "access-next"},
  { binding = "Galaxy", service = "galaxy-next"},
]

[env.next.build]
  command = "yarn build"

[env.current]
routes = [
  { pattern = "passport-current.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-current"},
  { binding = "Access", service = "access-current"},
  { binding = "Galaxy", service = "galaxy-current"},
]

[env.current.build]
  command = "yarn build"