# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
main = "./build/index.js"
name = "passport"
workers_dev = false
compatibility_flags = ["streams_enable_constructors"]
logpush = true

# Services binding for local development
services = [
  { binding = "Account", service = "account" },
  { binding = "Access", service = "access" },
  { binding = "Address", service = "address" },
  { binding = "Starbase", service = "starbase" },
  { binding = "Images", service = "images" },
  { binding = "Passport", service = "passport" },
]

[site]
bucket = "./public"

[build]
command = "yarn build -- --sourcemap"

[dev]
port = 10001
inspector_port = 11001
local_protocol = "http"

[vars]
PROFILE_APP_URL = "http://localhost:10003"
CONSOLE_APP_URL = "http://localhost:10002"
PASSPORT_REDIRECT_URL = "http://localhost:10001/connect/token"
COOKIE_DOMAIN = "localhost"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/twitter/callback"
INTERNAL_MICROSOFT_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/microsoft/callback"
INTERNAL_APPLE_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/apple/callback"
INTERNAL_DISCORD_OAUTH_CALLBACK_URL = "http://localhost:10001/connect/discord/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
JWKS_INTERNAL_URL_BASE = "http://127.0.0.1:10001/.well-known/jwks.json"


[env.dev]
routes = [
  { pattern = "passport-dev.rollup.id", custom_domain = true, zone_name = "rollup.id" },
  { pattern = "passport-dev.pz3r0.com", custom_domain = true, zone_name = "pz3r0.com" },

]
services = [
  { binding = "Account", service = "account-dev" },
  { binding = "Access", service = "access-dev" },
  { binding = "Address", service = "address-dev" },
  { binding = "Starbase", service = "starbase-dev" },
  { binding = "Images", service = "images-dev" },
  { binding = "Passport", service = "passport-dev" },
]

[env.dev.vars]
PROFILE_APP_URL = "https://my-dev.rollup.id"
CONSOLE_APP_URL = "https://console-dev.rollup.id"
PASSPORT_REDIRECT_URL = "https://passport-dev.rollup.id/connect/token"
COOKIE_DOMAIN = "rollup.id"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "https://passport-dev.rollup.id/connect/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "https://passport-dev.rollup.id/connect/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport-dev.rollup.id/connect/twitter/callback"
INTERNAL_APPLE_OAUTH_CALLBACK_URL = "https://passport-dev.rollup.id/connect/apple/callback"
INTERNAL_MICROSOFT_OAUTH_CALLBACK_URL = "https://passport-dev.rollup.id/connect/microsoft/callback"
INTERNAL_DISCORD_OAUTH_CALLBACK_URL = "https://passport-dev.rollup.id/connect/discord/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
JWKS_INTERNAL_URL_BASE = "https://passport-dev.pz3r0.com/.well-known/jwks.json"

[env.next]
routes = [
  { pattern = "passport-next.rollup.id", custom_domain = true, zone_name = "rollup.id" },
  { pattern = "passport-next.pz3r0.com", custom_domain = true, zone_name = "pz3r0.com" },
]
services = [
  { binding = "Account", service = "account-next" },
  { binding = "Access", service = "access-next" },
  { binding = "Address", service = "address-next" },
  { binding = "Starbase", service = "starbase-next" },
  { binding = "Images", service = "images-next" },
  { binding = "Passport", service = "passport-next" },

]

[env.next.vars]
PROFILE_APP_URL = "https://my-next.rollup.id"
CONSOLE_APP_URL = "https://console-next.rollup.id"
PASSPORT_REDIRECT_URL = "https://passport-next.rollup.id/connect/token"
COOKIE_DOMAIN = "rollup.id"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "https://passport-next.rollup.id/connect/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "https://passport-next.rollup.id/connect/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport-next.rollup.id/connect/twitter/callback"
INTERNAL_APPLE_OAUTH_CALLBACK_URL = "https://passport-next.rollup.id/connect/apple/callback"
INTERNAL_MICROSOFT_OAUTH_CALLBACK_URL = "https://passport-next.rollup.id/connect/microsoft/callback"
INTERNAL_DISCORD_OAUTH_CALLBACK_URL = "https://passport-next.rollup.id/connect/discord/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-X7ZN16M4NB"
JWKS_INTERNAL_URL_BASE = "https://passport-next.pz3r0.com/.well-known/jwks.json"

[env.next.build]
command = "yarn build"

[env.current]
routes = [
  { pattern = "passport.rollup.id", custom_domain = true, zone_name = "rollup.id" },
  { pattern = "passport.pz3r0.com", custom_domain = true, zone_name = "pz3r0.com" },
]
services = [
  { binding = "Account", service = "account-current" },
  { binding = "Access", service = "access-current" },
  { binding = "Address", service = "address-current" },
  { binding = "Starbase", service = "starbase-current" },
  { binding = "Images", service = "images-current" },
  { binding = "Passport", service = "passport-current" },

]

[env.current.vars]
PROFILE_APP_URL = "https://my.rollup.id"
CONSOLE_APP_URL = "https://console.rollup.id"
PASSPORT_REDIRECT_URL = "https://passport.rollup.id/connect/token"
COOKIE_DOMAIN = "rollup.id"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "https://passport.rollup.id/connect/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "https://passport.rollup.id/connect/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport.rollup.id/connect/twitter/callback"
INTERNAL_APPLE_OAUTH_CALLBACK_URL = "https://passport.rollup.id/connect/apple/callback"
INTERNAL_MICROSOFT_OAUTH_CALLBACK_URL = "https://passport.rollup.id/connect/microsoft/callback"
INTERNAL_DISCORD_OAUTH_CALLBACK_URL = "https://passport.rollup.id/connect/discord/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-675VJMWSRY"
JWKS_INTERNAL_URL_BASE = "https://passport.pz3r0.com/.well-known/jwks.json"

[env.current.build]
command = "yarn build"
