# projects/console/wrangler.toml

name = "console"

workers_dev = false
main = "./build/index.js"
compatibility_date = "2022-04-05"

services = [
  { binding = "Starbase", service = "starbase"},
  { binding = "Images", service = "images" },
  { binding = "Galaxy", service = "galaxy"}
]

# development
# -----------------------------------------------------------------------------

[dev]
port = 9898
local_protocol = "http"


# Environment Variables
# -----------------------------------------------------------------------------
# NB: environment variable configuration is not inherited; they should be set
# independently for each environment.

[vars]
DEPLOY_ENV = "local"
PASSPORT_URL = "http://localhost:9696"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
THREEID_APP_URL = "http://localhost:9797"
PASSPORT_REDIRECT_URL = "http://localhost:9696/authenticate/token"
COOKIE_DOMAIN = "localhost"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/twitter/callback"
INTERNAL_MICROSOFT_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/microsoft/callback"

# Site
# -----------------------------------------------------------------------------

[site]
  bucket = "./public"

# Build
# -----------------------------------------------------------------------------

[build]
  command = "yarn build -- --sourcemap"

# Environment: dev
# -----------------------------------------------------------------------------



[env.dev]

services = [
  { binding = "Starbase", service = "starbase-dev"},
  { binding = "Images", service = "images-dev" },
  { binding = "Galaxy", service = "galaxy-dev" },
]


# kv_namespaces = [
#   { binding = "SESSIONS", id = "719906291cbf4079a0c30cbed684208d", preview_id = "ded590c8008d4a77a42ba53a1ce23003" },
# ]

routes = [
  { pattern = "console-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
]

[env.dev.vars]
DEPLOY_ENV = "dev"
PASSPORT_URL = "https://passport-dev.threeid.xyz"
COOKIE_DOMAIN = "threeid.xyz"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
THREEID_APP_URL = "https://my-dev.threeid.xyz"
PASSPORT_REDIRECT_URL = "https://passport-dev.threeid.xyz/authenticate/token"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://passport-dev.threeid.xyz/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://passport-dev.threeid.xyz/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport-dev.threeid.xyz/authenticate/twitter/callback"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
  { binding = "Starbase", service = "starbase-next"},
  { binding = "Images", service = "images-next" },
  { binding = "Galaxy", service = "galaxy-next" },
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "6c6ca075005747e3873043cdf346f438" },
# ]

routes = [
  { pattern = "console-next.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
]

[env.next.build]
  command = "yarn build"

[env.next.vars]
DEPLOY_ENV = "next"
PASSPORT_URL = "https://passport-next.threeid.xyz"
COOKIE_DOMAIN = "threeid.xyz"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-X7ZN16M4NB"
THREEID_APP_URL = "https://my-next.threeid.xyz"
PASSPORT_REDIRECT_URL = "https://passport-next.threeid.xyz/authenticate/token"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://passport-next.threeid.xyz/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://passport-next.threeid.xyz/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport-next.threeid.xyz/authenticate/twitter/callback"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

services = [
  { binding = "Starbase", service = "starbase-current", environment = "production" },
  { binding = "Galaxy", service = "galaxy-current" },
  { binding = "Images", service = "images-current" },
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "593c81a8b57347a4b30368eabee072ef" },
# ]

routes = [
  { pattern = "console.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
]

[env.current.build]
  command = "yarn build"


[env.current.vars]
DEPLOY_ENV = "current"
PASSPORT_URL = "https://passport.threeid.xyz"
COOKIE_DOMAIN = "threeid.xyz"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-675VJMWSRY"
THREEID_APP_URL = "https://my.threeid.xyz"
PASSPORT_REDIRECT_URL = "https://passport.threeid.xyz/authenticate/token"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://passport.threeid.xyz/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://passport.threeid.xyz/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport.threeid.xyz/authenticate/twitter/callback"
