name = "console"
main = "./build/index.js"
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]
logpush = true
workers_dev = false

[build]
command = "yarn build"

[site]
bucket = "./public"

[env.dev]
routes = [
  { pattern = "console-dev.rollup.id", custom_domain = true, zone_name = "rollup.id" },
]

services = [
  { binding = "Core", service = "core-dev" },
  { binding = "Images", service = "images-dev" },
]

[env.dev.vars]
PASSPORT_URL = "https://passport-dev.rollup.id"
COOKIE_DOMAIN = "rollup.id"
STORAGE_NAMESPACE = "console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
PROFILE_APP_URL = "https://my-dev.rollup.id"
WALLET_CONNECT_PROJECT_ID = "249578b973e49826abb32d2ad263e2a3"
CONSOLE_URL = "https://console-dev.rollup.id"
POSTHOG_API_KEY = "phc_f7q7V62YWsS0FKyIRxO36xyUMFYJ8oahurHPBAXkGe5"
POSTHOG_PROXY_HOST = "https://analytics.rollup.id"
