name = "console"

workers_dev = false
main = "./build/index.js"
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]
logpush = true

services = [
  { binding = "Core", service = "core" },
  { binding = "Images", service = "images" },
]

[dev]
port = 10002
inspector_port = 11002
local_protocol = "http"

[vars]
PASSPORT_URL = "http://localhost:10001"
STORAGE_NAMESPACE = "console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
PROFILE_APP_URL = "http://localhost:10003"
COOKIE_DOMAIN = "localhost"
WALLET_CONNECT_PROJECT_ID = "36efbf71d7586e254d72041a15a42078"
CONSOLE_URL = "http://localhost:10002"
POSTHOG_API_KEY = "phc_f7q7V62YWsS0FKyIRxO36xyUMFYJ8oahurHPBAXkGe5"
POSTHOG_PROXY_HOST = "https://analytics.rollup.id"
STRIPE_PUBLISHABLE_KEY = "pk_test_51NFemUKJnr9qdtTa8eIGrDR1QtpUTAwewEejO13AAnugHFAAhOWbSWKah4l66gGKs2BO6ITlax5lftx337yedqMb00aWdwi16G"

[site]
bucket = "./public"

# [build]
# command = "yarn build -- --sourcemap"
