# projects/console/wrangler.toml

name = "starbase"

workers_dev = true
main = "./build/index.js"
compatibility_date = "2022-04-05"

services = [
  { binding = "Starbase", service = "starbase"}
]

# development
# -----------------------------------------------------------------------------

[dev]
port = 9898
local_protocol = "http"

# Secrets
# -----------------------------------------------------------------------------
# Set these secrets using the wrangler CLI:
# $ echo <VALUE> | wrangler secret put <NAME>

# Required secrets:
# - SESSION_SECRET

# Environment Variables
# -----------------------------------------------------------------------------
# NB: environment variable configuration is not inherited; they should be set
# independently for each environment.

[vars]
PASSPORT_URL = "http://localhost:9696"
COOKIE_DOMAIN = "localhost"

# Site
# -----------------------------------------------------------------------------

[site]
  bucket = "./public"

# Build
# -----------------------------------------------------------------------------

[build]
  command = "yarn build -- --sourcemap"

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]

services = [
  { binding = "Starbase", service = "starbase-dev"}
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "719906291cbf4079a0c30cbed684208d", preview_id = "ded590c8008d4a77a42ba53a1ce23003" },
# ]

routes = [
  { pattern = "console-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
]

[env.dev.vars]
DEPLOY_ENV = "dev"
PASSPORT_URL = "https://passport-dev.threeid.xyz"
COOKIE_DOMAIN = "dev.threeid.xyz"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
  { binding = "Starbase", service = "starbase-next"}
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "6c6ca075005747e3873043cdf346f438" },
# ]

routes = [
  { binding = "Starbase", service = "starbase-current"}
]

[env.next.build]
  command = "yarn build"

[env.next.vars]
DEPLOY_ENV = "next"
PASSPORT_URL = "https://passport-next.threeid.xyz"
COOKIE_DOMAIN = "next.threeid.xyz"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

services = [
  { binding = "STARBASE", service = "starbase", environment = "production" }
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "593c81a8b57347a4b30368eabee072ef" },
# ]

routes = [
  { pattern = "console.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" }
]

[env.current.build]
  command = "yarn build"


[env.current.vars]
DEPLOY_ENV = "current"
PASSPORT_URL = "https://passport.threeid.xyz"
COOKIE_DOMAIN = "threeid.xyz"
