# projects/console/wrangler.toml

name = "console"

workers_dev = false
main = "./build/index.js"
compatibility_date = "2022-04-05"
compatibility_flags = [ "streams_enable_constructors" ]


services = [
  { binding = "Starbase", service = "starbase"},
  { binding = "Images", service = "images" },
  { binding = "Galaxy", service = "galaxy"},
  { binding = "Account", service = "account"}
]

# development
# -----------------------------------------------------------------------------

[dev]
port = 10002
inspector_port = 11002
local_protocol = "http"


# Environment Variables
# -----------------------------------------------------------------------------
# NB: environment variable configuration is not inherited; they should be set
# independently for each environment.

[vars]
DEPLOY_ENV = "local"
PASSPORT_URL = "http://localhost:10001"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
PROFILE_APP_URL = "http://localhost:10003"
COOKIE_DOMAIN = "localhost"

# Site
# -----------------------------------------------------------------------------

[site]
  bucket = "./public"

# Build
# -----------------------------------------------------------------------------

[build]
  command = "yarn build -- --sourcemap"

# Environment: dev
# -----------------------------------------------------------------------------



[env.dev]

services = [
  { binding = "Starbase", service = "starbase-dev"},
  { binding = "Images", service = "images-dev" },
  { binding = "Galaxy", service = "galaxy-dev" },
  { binding = "Account", service = "account-dev"}
]


# kv_namespaces = [
#   { binding = "SESSIONS", id = "719906291cbf4079a0c30cbed684208d", preview_id = "ded590c8008d4a77a42ba53a1ce23003" },
# ]

routes = [
  { pattern = "console-dev.rollup.id", custom_domain = true, zone_name = "rollup.id" },
]

[env.dev.vars]
DEPLOY_ENV = "dev"
PASSPORT_URL = "https://passport-dev.rollup.id"
COOKIE_DOMAIN = "rollup.id"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"
PROFILE_APP_URL = "https://my-dev.rollup.id"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
  { binding = "Starbase", service = "starbase-next"},
  { binding = "Images", service = "images-next" },
  { binding = "Galaxy", service = "galaxy-next" },
  { binding = "Account", service = "account-next"}
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "6c6ca075005747e3873043cdf346f438" },
# ]

routes = [
  { pattern = "console-next.rollup.id", custom_domain = true, zone_name = "rollup.id" },
]

[env.next.build]
  command = "yarn build"

[env.next.vars]
DEPLOY_ENV = "next"
PASSPORT_URL = "https://passport-next.rollup.id"
COOKIE_DOMAIN = "rollup.id"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-X7ZN16M4NB"
PROFILE_APP_URL = "https://my-next.rollup.id"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

services = [
  { binding = "Starbase", service = "starbase-current", environment = "production" },
  { binding = "Galaxy", service = "galaxy-current" },
  { binding = "Images", service = "images-current" },
  { binding = "Account", service = "account-current"}
]

# kv_namespaces = [
#   { binding = "SESSIONS", id = "593c81a8b57347a4b30368eabee072ef" },
# ]

routes = [
  { pattern = "console.rollup.id", custom_domain = true, zone_name = "rollup.id" },
]

[env.current.build]
  command = "yarn build"


[env.current.vars]
DEPLOY_ENV = "current"
PASSPORT_URL = "https://passport.rollup.id"
COOKIE_DOMAIN = "rollup.id"
STORAGE_NAMESPACE="console"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-675VJMWSRY"
PROFILE_APP_URL = "https://my.rollup.id"
