# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

main = "./build/index.js"

name = "threeid-dapp"

# The default environment
# ------------------------------------------------------------------------------
# name = "three-id-dev"
# # Whether or not the worker should be deployed to *.workers.dev. Can use
# # either route or workers_dev, but not both.
# workers_dev = true
# routes = [
#   "3id-dev.kubelt.com/*",
# ]
kv_namespaces = [
]

# Services binding for local development
services = [
  { binding = "OORT", service = "oort"},
  { binding = "GALAXY", service = "galaxy"},
  { binding = "ICONS", service = "icons-dev"},
]

[vars]
ENS_RESOLVER_URL = "https://api.ensideas.com/ens/resolve/"
PASSPORT_URL = "http://localhost:9696"
COOKIE_DOMAIN = "localhost"

[site]
  bucket = "./public"

[build]
  command = "yarn build -- --sourcemap"

[dev]
port = 31337
local_protocol = "http"

# dev (development)
# ------------------------------------------------------------------------------
[env.dev]
kv_namespaces = [
]
routes = [
  { pattern = "app-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "OORT", service = "oort-devnet"},
  { binding = "GALAXY", service = "galaxy-dev"},
  { binding = "ICONS", service = "icons-dev"},
]
[env.dev.vars]
  PASSPORT_URL = "https://passport-dev.threeid.xyz"
  COOKIE_DOMAIN = "dev.threeid.xyz"

# next (staging)
# ------------------------------------------------------------------------------
[env.next]
routes = [
  { pattern = "app-next.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
kv_namespaces = [
]
services = [
  { binding = "OORT", service = "oort-testnet"},
  { binding = "GALAXY", service = "galaxy-next"},
  { binding = "ICONS", service = "icons-next"},
]
[env.next.build]
  command = "yarn build"
[env.next.vars]
  PASSPORT_URL = "https://passport-next.threeid.xyz"
  COOKIE_DOMAIN = "next.threeid.xyz"


# current (production)
# ------------------------------------------------------------------------------
[env.current]
routes = [
  { pattern = "app.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
kv_namespaces = [
]
services = [
  { binding = "OORT", service = "oort-mainnet"},
  { binding = "GALAXY", service = "galaxy-current"},
  { binding = "ICONS", service = "icons-current"},
]
[env.current.build]
  command = "yarn build"
[env.current.vars]
  PASSPORT_URL = "https://passport.threeid.xyz"
  COOKIE_DOMAIN = "threeid.xyz"
