name = "access"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false
logpush = true

durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges" },
  { binding = "Starbase", service = "starbase" },
  { binding = "Account", service = "account" },
  { binding = "Address", service = "address" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[dev]
port = 10101
inspector_port = 11101
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges-dev" },
  { binding = "Starbase", service = "starbase-dev" },
  { binding = "Account", service = "account-dev" },
  { binding = "Address", service = "address-dev" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.next]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges-next" },
  { binding = "Starbase", service = "starbase-next" },
  { binding = "Account", service = "account-next" },
  { binding = "Address", service = "address-next" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.current]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges-current" },
  { binding = "Starbase", service = "starbase-current" },
  { binding = "Account", service = "account-current" },
  { binding = "Address", service = "address-current" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[[migrations]]
tag = "v0"
new_classes = ["Access", "Authorization"]
