name = "access"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges" },
  { binding = "Starbase", service = "starbase" },
  { binding = "Account", service = "account" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[vars]
INTERNAL_JWT_ISS = "http://localhost:9696"

[dev]
port = 9393
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges-dev" },
  { binding = "Starbase", service = "starbase-dev" },
  { binding = "Account", service = "account-dev" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.dev.vars]
INTERNAL_JWT_ISS = "https://passport-dev.rollup.id"

[env.next]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges-next" },
  { binding = "Starbase", service = "starbase-next" },
  { binding = "Account", service = "account-next" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.next.vars]
INTERNAL_JWT_ISS = "https://passport-next.rollup.id"

[env.current]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "Edges", service = "edges-current" },
  { binding = "Starbase", service = "starbase-current" },
  { binding = "Account", service = "account-current" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.current.vars]
INTERNAL_JWT_ISS = "https://passport.rollup.id"

[[migrations]]
tag = "v0"
new_classes = ["Access", "Authorization"]
