name = "edges"
main = "src/index.ts"
compatibility_date = "2022-11-24"
node_compat = true
logpush = true


# #############################################################################
# NB: we don't supply an external route for this service as it is
# intended to be service-bound.
# #############################################################################

# Don't automatically expose this service at:
# <worker-name>.<account-name>.workers.dev.
workers_dev = false

# D1 Databases
# -----------------------------------------------------------------------------

[[d1_databases]]
binding = "EDGES"
database_name = "edges-v2"
database_id = "d5dc9f97-0f8e-4af7-90dd-cb84e44309bd"
migrations_dir = "migrations"

# Secrets
# -----------------------------------------------------------------------------

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# N/A

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

# Environment
# -----------------------------------------------------------------------------

[vars]
ENVIRONMENT = "local"

# Dev
# -----------------------------------------------------------------------------

[dev]
port = 10501
inspector_port = 11501
local_protocol = "http"

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]
d1_databases = [
  { binding = "EDGES", database_name = "edges-v2-dev", database_id = "bd11ba92-bfcf-4d37-8224-d57467cced48", migrations_dir = "migrations" },
]

[env.dev.vars]
ENVIRONMENT = "dev"

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

d1_databases = [
  { binding = "EDGES", database_name = "edges-v2-next", database_id = "058ddc84-7734-47ca-a84b-7f325c5336f7", migrations_dir = "migrations" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.next.vars]
ENVIRONMENT = "next"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

d1_databases = [
  { binding = "EDGES", database_name = "edges-v2-current", database_id = "825ee9f1-8de8-4f73-a0e0-1998feea3d7f", migrations_dir = "migrations" },
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent" },
]

unsafe.bindings = [{ type = "metadata", name = "ServiceDeploymentMetadata" }]

[env.current.vars]
ENVIRONMENT = "current"
