name = "edges"
main = "src/index.ts"
compatibility_date = "2022-11-24"
node_compat = true


# #############################################################################
# NB: we don't supply an external route for this service as it is
# intended to be service-bound.
# #############################################################################

# Don't automatically expose this service at:
# <worker-name>.<account-name>.workers.dev.
workers_dev = false

# Services
# -----------------------------------------------------------------------------
# A list of other Clouflare services bound to this service.

services = [
]

# Durable Objects
# -----------------------------------------------------------------------------

durable_objects.bindings = [
]

# KV
# -----------------------------------------------------------------------------

kv_namespaces = [
]

# D1 Databases
# -----------------------------------------------------------------------------

[[d1_databases]]
binding = "EDGES"
database_name = "edges"
database_id = "0f35adf4-7b94-49bf-93c1-e675f3db3533"

# Secrets
# -----------------------------------------------------------------------------

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# N/A

# Environment
# -----------------------------------------------------------------------------

[vars]
ENVIRONMENT = "local"

# Dev
# -----------------------------------------------------------------------------

[dev]
port = 8686
local_protocol = "http"

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]

services = [
]

durable_objects.bindings = [
]

kv_namespaces = [
]

d1_databases = [
]

[env.dev.vars]
ENVIRONMENT = "dev"

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

services = [
]

durable_objects.bindings = [
]

kv_namespaces = [
]

d1_databases = [
]

[env.next.vars]
ENVIRONMENT = "next"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

services = [
]

durable_objects.bindings = [
]

kv_namespaces = [
]

d1_databases = [
]

[env.current.vars]
ENVIRONMENT = "current"
