name = "edges"
main = "src/index.ts"
compatibility_date = "2022-11-24"
node_compat = true


# #############################################################################
# NB: we don't supply an external route for this service as it is
# intended to be service-bound.
# #############################################################################

# Don't automatically expose this service at:
# <worker-name>.<account-name>.workers.dev.
workers_dev = false

# D1 Databases
# -----------------------------------------------------------------------------

[[d1_databases]]
binding = "EDGES"
database_name = "edges"
database_id = "d5dc9f97-0f8e-4af7-90dd-cb84e44309bd"
migrations_dir = "migrations"

# Secrets
# -----------------------------------------------------------------------------

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# N/A

# Environment
# -----------------------------------------------------------------------------

[vars]
ENVIRONMENT = "local"

# Dev
# -----------------------------------------------------------------------------

[dev]
port = 8686
local_protocol = "http"

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalytics"  },
]

# Environment: dev
# -----------------------------------------------------------------------------

[env.dev]
d1_databases = [
  { binding = "EDGES", database_name = "edges-dev", database_id = "d5dc9f97-0f8e-4af7-90dd-cb84e44309bd", migrations_dir = "migrations" }
]

[env.dev.vars]
ENVIRONMENT = "dev"

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsDev"  },
]

# Environment: next
# -----------------------------------------------------------------------------

[env.next]

d1_databases = [
  { binding = "EDGES", database_name = "edges-next", database_id = "35573801-81b5-4c57-8a79-286343476d98", migrations_dir = "migrations" }
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsNext"  },
]

[env.next.vars]
ENVIRONMENT = "next"

# Environment: current
# -----------------------------------------------------------------------------

[env.current]

d1_databases = [
  { binding = "EDGES", database_name = "edges-next", database_id = "27b77920-664e-4e52-84ca-72be96b9a3fd", migrations_dir = "migrations" }
]

analytics_engine_datasets = [
  { binding = "Analytics", dataset = "PlatformAnalyticsCurrent"  },
]

[env.current.vars]
ENVIRONMENT = "current"
