# .github/workflows/chromatic.yml

# Workflow name
name: 'Storybook'

# Event for the workflow
on:
  pull_request:
    branches:
      - main

# List of jobs
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      profile: ${{ steps.changes.outputs.profile }}
      passport: ${{ steps.changes.outputs.passport }}
      console: ${{ steps.changes.outputs.console }}
      design: ${{ steps.changes.outputs.design }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: storybook
        with:
          filters: |
            profile:
              - 'apps/profile/app/components/**'
            passport:
              - 'apps/passport/app/components/**'
            console:
              - 'apps/console/app/components/**'
            design: 
              - 'packages/design-system/src/**'

  chromatic-deployment-design-system:
    needs: changes
    if: needs.changes.outputs.storybook == 'true'
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.TOKEN_CHROMATIC_DESIGN_SYSTEM_PROJECT }}
          onlyChanged: true
          workingDir: packages/design-system
  chromatic-deployment-passport:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.TOKEN_CHROMATIC_PASSPORT_PROJECT }}
          onlyChanged: true
          workingDir: apps/passport
  chromatic-deployment-profile:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.TOKEN_CHROMATIC_THREEID_PROJECT }}
          onlyChanged: true
          workingDir: apps/profile
  chromatic-deployment-console:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.TOKEN_CHROMATIC_CONSOLE_PROJECT }}
          onlyChanged: true
          workingDir: apps/console
