# .github/workflows/main-edges.yaml
---
name: Edges

on:
  push:
    branches:
      - main
      - feat/edges

defaults:
  run:
    working-directory: ./platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Drop edges D1 Database
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'platform/edges'
          command: d1 delete --env dev edges-dev
          environment: 'dev'
          # This causes secrets to be set as if by: $ wrangler secret put.
          # Each supplied name must be defined in the env: config stanza.
          secrets: |
            CLOUDFLARE_ACCOUNT_ID
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy edges D1 Database
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'platform/edges'
          command: d1 execute --env dev edges-dev --file=./edges.sql
          environment: 'dev'
          # This causes secrets to be set as if by: $ wrangler secret put.
          # Each supplied name must be defined in the env: config stanza.
          secrets: |
            CLOUDFLARE_ACCOUNT_ID
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy edges dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'platform/edges'
          command: publish --env dev
          environment: 'dev'
          # This causes secrets to be set as if by: $ wrangler secret put.
          # Each supplied name must be defined in the env: config stanza.
          secrets: |
            CLOUDFLARE_ACCOUNT_ID
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
