---
name: Redeem

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./projects

jobs:
  build-publish-test-redeem-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build projects.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include redeem run test

      - name: Deploy to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ADMIN_ACCOUNT_ID }}
          workingDirectory: 'projects/redeem'
          command: publish --env dev
          environment: 'dev'
          secrets: |
            SESSION_SECRET
            DATADOG_CLIENT_TOKEN
            DATADOG_APPLICATION_ID
            DATADOG_ENV
            DATADOG_SERVICE_NAME
            NFTAR_URL
            NFTAR_AUTHORIZATION
            INVITE_CONTRACT_ADDRESS
            MINTPFP_CONTRACT_ADDRESS
            CHAIN_ID
            NFTAR_CHAIN_ID
            INVITE_OPERATOR_PRIVATE_KEY
            TWITTER_BEARER_TOKEN
            ALCHEMY_API_KEY
            ALCHEMY_API_URL
            ALCHEMY_NFT_URL
        env:
          SESSION_SECRET: 'secret'
          ADMIN_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          # The Datadog client token.
          DATADOG_CLIENT_TOKEN: ${{ secrets.GET_THREEID_DATADOG_CLIENT_TOKEN }}
          DATADOG_APPLICATION_ID: ${{ secrets.GET_THREEID_DATADOG_APPLICATION_ID }}
          DATADOG_ENV: development
          DATADOG_SERVICE_NAME: get-3id
          # The Cloudflare API token used by wrangler.
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          NFTAR_URL: ${{ secrets.NFTAR_TEST_URL }}
          NFTAR_AUTHORIZATION: ${{ secrets.NFTAR_TEST_AUTHORIZATION }}
          INVITE_CONTRACT_ADDRESS: ${{ secrets.INVITE_TEST_CONTRACT_ADDRESS }}
          MINTPFP_CONTRACT_ADDRESS: ${{ secrets.MINT_PFP_TEST_CONTRACT_ADDRESS }}
          CHAIN_ID: 5
          NFTAR_CHAIN_ID: 5
          INVITE_OPERATOR_PRIVATE_KEY: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_DEV_BEARER_TOKEN }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_GOERLI_API_KEY }}
          ALCHEMY_API_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
          ALCHEMY_NFT_URL: ${{ secrets.ALCHEMY_GOERLI_NFT_URL }}
