# .github/workflows/main-console.yaml
---
name: Console

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-console-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include console run test

      - name: Deploy Console to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/console'
          command: publish --env dev
          environment: 'dev'
          secrets: |
            SECRET_SESSION_SALT
        env:
          NODE_ENV: 'development'
          # A secret used for session encryption.
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_DEV }}
          # CF_ROUTE: https://console-dev.kubelt.com/*

      - name: Setup Playwright
        with:
          workingDirectory: 'apps/console'
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        with:
          workingDirectory: 'apps/console'
        env:
          PLAYWRIGHT_BASE_URL: https://console-dev.rollup.id
          INTERNAL_TWITTER_USERNAME_TEST: ${{ secrets.INTERNAL_TWITTER_USERNAME_TEST }}
          INTERNAL_TWITTER_PASSWORD_TEST: ${{ secrets.INTERNAL_TWITTER_PASSWORD_TEST }}
          INTERNAL_GITHUB_USERNAME_TEST: ${{ secrets.INTERNAL_GITHUB_USERNAME_TEST }}
          INTERNAL_GITHUB_PASSWORD_TEST: ${{ secrets.INTERNAL_GITHUB_PASSWORD_TEST }}
          INTERNAL_GOOGLE_USERNAME_TEST: ${{ secrets.INTERNAL_GOOGLE_USERNAME_TEST }}
          INTERNAL_GOOGLE_PASSWORD_TEST: ${{ secrets.INTERNAL_GOOGLE_PASSWORD_TEST }}
          INTERNAL_MICROSOFT_USERNAME_TEST: ${{ secrets.INTERNAL_MICROSOFT_USERNAME_TEST }}
          INTERNAL_MICROSOFT_PASSWORD_TEST: ${{ secrets.INTERNAL_MICROSOFT_PASSWORD_TEST }}
          INTERNAL_APPLE_USERNAME_TEST: ${{ secrets.INTERNAL_APPLE_USERNAME_TEST }}
          INTERNAL_APPLE_PASSWORD_TEST: ${{ secrets.INTERNAL_APPLE_PASSWORD_TEST }}
          INTERNAL_DISCORD_USERNAME_TEST: ${{ secrets.INTERNAL_DISCORD_USERNAME_TEST }}
          INTERNAL_DISCORD_PASSWORD_TEST: ${{ secrets.INTERNAL_DISCORD_PASSWORD_TEST }}
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          workingDirectory: 'apps/console'
          name: playwright-report
          path: playwright-report/
          retention-days: 30
