---
name: Smart Contracts
on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./smartcontracts

env:
  # TODO: fix naming of env vars
  CHAIN: 'ethereum'
  CHAIN_ID: 5
  OORT_URL: oort-devnet.kubelt.com
  ALCHEMY_NETWORK: 'ETH_MAINNET'
  NFTAR_API_KEY: 'test'

jobs:
  build-test-smartcontracts:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build smartcontracts.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      # - name: Test
      #   run: yarn test
