# .github/workflows/main-console.yaml
---
name: Console

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-console-dev:
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include console run test

      - name: Deploy Console to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          wranglerVersion: '3.2.0'
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/console'
          command: publish --config wrangler.dev.toml
          environment: 'dev'
          secrets: |
            SECRET_SESSION_KEY
            SECRET_SESSION_SALT
            SECRET_STRIPE_API_KEY
            SECRET_STRIPE_WEBHOOK_SECRET
            SECRET_STRIPE_PRO_PLAN_ID
        env:
          NODE_ENV: 'development'
          # A secret used for session encryption.
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_DEV }}
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_DEV }}
          # CF_ROUTE: https://console-dev.kubelt.com/*
          SECRET_STRIPE_API_KEY: ${{ secrets.SECRET_STRIPE_API_KEY_DEV }}
          SECRET_STRIPE_WEBHOOK_SECRET: ${{ secrets.SECRET_STRIPE_WEBHOOK_SECRET_DEV }}
          SECRET_STRIPE_PRO_PLAN_ID: ${{ secrets.SECRET_STRIPE_PRO_PLAN_ID_DEV }}

      - name: Setup Playwright
        working-directory: 'apps/console'
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        working-directory: 'apps/console'
        env:
          INTERNAL_PLAYWRIGHT_BASE_URL: https://console-dev.rollup.id
          INTERNAL_PLAYWRIGHT_TEST_URL: ${{ secrets.INTERNAL_PLAYWRIGHT_TEST_URL }}
          INTERNAL_EMAIL_TEST_USERNAME: ${{ secrets.INTERNAL_EMAIL_TEST_USERNAME}}
          SECRET_TEST_API_TOKEN: ${{ secrets.SECRET_TEST_API_TEST_TOKEN }}
          INTERNAL_GITHUB_TEST_USERNAME: ${{ secrets.INTERNAL_GITHUB_TEST_USERNAME }}
          SECRET_GITHUB_TEST_USER_PASSWORD: ${{ secrets.SECRET_GITHUB_TEST_USER_PASSWORD }}
          INTERNAL_MICROSOFT_TEST_USERNAME: ${{ secrets.INTERNAL_MICROSOFT_TEST_USERNAME }}
          SECRET_MICROSOFT_TEST_USER_PASSWORD: ${{ secrets.SECRET_MICROSOFT_TEST_USER_PASSWORD }}
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/console/playwright-report/
          retention-days: 30
