---
name: NFTAR
on:
  push:
    branches:
      - main

jobs:
  build-test-nftar-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules--${{ hashFiles('yarn.lock') }}
      - uses: cachix/install-nix-action@v18
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
        if: steps.cache-modules.outputs.cache-hit != 'true'
      - uses: actions/setup-node@v3
        if: steps.cache-modules.outputs.cache-hit == 'true'
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
        env:
          CHAIN: "ethereum"
          CHAIN_ID: 5
          OORT_URL: oort-devnet.kubelt.com
          STORAGE_KEY: ${{ secrets.NFT_STORAGE_DEV }}
          WALLET_PRIVATE_KEY: ${{ secrets.MINT_PFP_TEST_OPERATOR_PRIVATE_KEY }} # TODO: this is a bad env name
          ALCHEMY_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_GOERLI_API_KEY }}
          ALCHEMY_NETWORK: "ETH_MAINNET"
          INVITE_CONTRACT_ADDRESS: ${{ secrets.INVITE_TEST_CONTRACT_ADDRESS }}
          PFP_CONTRACT_ADDRESS: ${{ secrets.MINT_PFP_TEST_CONTRACT_ADDRESS }}
          NFTAR_API_KEY: "test"
      # TODO: deploy
