---
name: Passport

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-passport-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Code Generation
        run: yarn gql

      - name: Test
        run: yarn workspaces foreach -i -v -t --include passport run test

      - name: Deploy to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/passport'
          command: publish --env dev
          environment: 'dev'
          secrets: |
            SESSION_SECRET
            ALCHEMY_KEY
        env:
          SESSION_SECRET: 'foobar'
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_PUBLIC_API_KEY }}
