name: Oort

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Install
        run: yarn workspaces focus -A

      - name: Test
        run: yarn workspaces foreach -i -v -t --include oort run test

      - name: Deploy Oort to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "platform/oort"
          command: publish --env devnet
          environment: "devnet"
          secrets: |
            SITE
            ENVIRONMENT
            DEBUG_TOKEN
            DATADOG_API_KEY
            DATADOG_APP_KEY
            ENS_CONTRACT_ADDRESS
            ALCHEMY_API_URL
            ALCHEMY_NFT_API_URL
            AUTH_JWT_ALG
            AUTH_JWT_TTL
            AUTH_NONCE_LENGTH
            AUTH_NONCE_TTL
        env:
          SITE: oort-devnet
          DEBUG_TOKEN: 1
          ENVIRONMENT: production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APPLICATION_ID }}
          ENS_CONTRACT_ADDRESS: ${{ secrets.ENS_CONTRACT_ADDRESS }}
          ALCHEMY_API_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
          ALCHEMY_NFT_API_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
          AUTH_JWT_ALG: ES256
          AUTH_JWT_TTL: 3600
          AUTH_NONCE_LENGTH: 24
          AUTH_NONCE_TTL: 600
