name: Oort

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: projects/oort

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules--${{ hashFiles('yarn.lock') }}
      - uses: cachix/install-nix-action@v18
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
      - uses: actions/setup-node@v3
        if: steps.cache-modules.outputs.cache-hit == 'true'
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install
      - run: yarn run wrangler:publish:devnet
        env:
          SITE: oort-devnet
          ENVIRONMENT: production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APPLICATION_ID }}
          ENS_CONTRACT_ADDRESS: ${{ secrets.ENS_CONTRACT_ADDRESS }}
          ALCHEMY_API_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
          ALCHEMY_NFT_API_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
