---
name: Passport

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-passport-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include passport run test

      - name: Deploy to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/passport'
          command: publish --env dev
          environment: 'dev'
          secrets: |
            SECRET_SESSION_SALT
            APIKEY_ALCHEMY_PUBLIC
            INTERNAL_GOOGLE_OAUTH_CLIENT_ID
            SECRET_GOOGLE_OAUTH_CLIENT_SECRET
            INTERNAL_GITHUB_OAUTH_CLIENT_ID
            SECRET_GITHUB_OAUTH_CLIENT_SECRET
            INTERNAL_TWITTER_OAUTH_CLIENT_ID
            SECRET_TWITTER_OAUTH_CLIENT_SECRET
            INTERNAL_MICROSOFT_OAUTH_CLIENT_ID
            SECRET_MICROSOFT_OAUTH_CLIENT_SECRET
            INTERNAL_APPLE_OAUTH_CLIENT_ID
            SECRET_APPLE_OAUTH_CLIENT_SECRET
            INTERNAL_DISCORD_OAUTH_CLIENT_ID
            SECRET_DISCORD_OAUTH_CLIENT_SECRET
        env:
          NODE_ENV: 'development'
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_DEV }}
          APIKEY_ALCHEMY_PUBLIC: ${{ secrets.APIKEY_ALCHEMY_PUBLIC_GOERLI }}
          INTERNAL_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.INTERNAL_GOOGLE_OAUTH_CLIENT_ID_DEV }}
          SECRET_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_GOOGLE_OAUTH_CLIENT_SECRET_DEV }}
          INTERNAL_GITHUB_OAUTH_CLIENT_ID: ${{ secrets.INTERNAL_GITHUB_OAUTH_CLIENT_ID_DEV }}
          SECRET_GITHUB_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_GITHUB_OAUTH_CLIENT_SECRET_DEV }}
          INTERNAL_TWITTER_OAUTH_CLIENT_ID: ${{ secrets.INTERNAL_TWITTER_OAUTH_CLIENT_ID_DEV }}
          SECRET_TWITTER_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_TWITTER_OAUTH_CLIENT_SECRET_DEV }}
          INTERNAL_MICROSOFT_OAUTH_CLIENT_ID: ${{ secrets.INTERNAL_MICROSOFT_OAUTH_CLIENT_ID_DEV }}
          SECRET_MICROSOFT_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_MICROSOFT_OAUTH_CLIENT_SECRET_DEV }}
          INTERNAL_APPLE_OAUTH_CLIENT_ID: ${{ secrets.INTERNAL_APPLE_OAUTH_CLIENT_ID_DEV }}
          SECRET_APPLE_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_APPLE_OAUTH_CLIENT_SECRET_DEV }}
          INTERNAL_DISCORD_OAUTH_CLIENT_ID: ${{ secrets.INTERNAL_DISCORD_OAUTH_CLIENT_ID_DEV }}
          SECRET_DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_DISCORD_OAUTH_CLIENT_SECRET_DEV }}
