---
name: Next Galaxy
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: ./platform

jobs:
  build-publish-test-galaxy-next:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Code Generation
        run: yarn gql

      - name: Test
        run: yarn workspaces foreach -i -v -t --include galaxy run test

      - name: Deploy to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'platform/galaxy'
          command: publish --env next
          environment: 'next'
          secrets: |
            ALCHEMY_KEY
        env:
          ADMIN_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          ALCHEMY_KEY: ${{ secrets.GALAXY_ALCHEMY_GOERLI_API_KEY}}
