---
name: Next Profile
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-profile-next:
    runs-on: ubuntu-latest
    environment: next
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include profile run test

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/profile'
          command: publish --config wrangler.next.toml
          environment: 'next'
          secrets: |
            SECRET_SESSION_KEY
            SECRET_SESSION_SALT
            PROFILE_CLIENT_ID
            PROFILE_CLIENT_SECRET
            APIKEY_ALCHEMY_ETH
            APIKEY_ALCHEMY_POLYGON
        env:
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_TEST }}
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_TEST }}
          PROFILE_CLIENT_ID: ${{ vars.INTERNAL_PROFILE_OAUTH_CLIENT_ID_NEXT }}
          PROFILE_CLIENT_SECRET: ${{ secrets.SECRET_PROFILE_OAUTH_CLIENT_SECRET_NEXT }}
          APIKEY_ALCHEMY_ETH: ${{ secrets.APIKEY_ALCHEMY_GALAXY_MAINNET }}
          APIKEY_ALCHEMY_POLYGON: ${{ secrets.APIKEY_ALCHEMY_POLYGON_MAINNET }}
