# .github/workflows/next-images.yaml
---
name: Next Images

on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: ./services

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build services.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      # - name: Test
      #   run: yarn workspaces foreach -i -v -t --include images run test

      - name: Deploy Images to Test Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'services/images'
          command: publish --env next
          environment: 'next'
          # This causes secrets to be set as if by: $ wrangler secret put.
          # Each supplied name must be defined in the env: config stanza.
          secrets: |
            INTERNAL_CLOUDFLARE_ACCOUNT_ID
            TOKEN_CLOUDFLARE_API
        env:
          INTERNAL_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          TOKEN_CLOUDFLARE_API: ${{ secrets.TOKEN_CLOUDFLARE_API }}
