---
name: Next Passport
on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-passport-next:
    runs-on: ubuntu-latest
    environment: next
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include passport run test

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          wranglerVersion: '3.2.0'
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/passport'
          command: publish --config wrangler.next.toml --env next
          environment: 'next'
          secrets: |
            SECRET_SESSION_KEY
            SECRET_SESSION_SALT
            APIKEY_ALCHEMY_PUBLIC
            INTERNAL_GOOGLE_OAUTH_CLIENT_ID
            SECRET_GOOGLE_OAUTH_CLIENT_SECRET
            INTERNAL_GITHUB_OAUTH_CLIENT_ID
            SECRET_GITHUB_OAUTH_CLIENT_SECRET
            INTERNAL_TWITTER_OAUTH_CLIENT_ID
            SECRET_TWITTER_OAUTH_CLIENT_SECRET
            INTERNAL_MICROSOFT_OAUTH_CLIENT_ID
            SECRET_MICROSOFT_OAUTH_CLIENT_SECRET
            INTERNAL_APPLE_OAUTH_CLIENT_ID
            SECRET_APPLE_OAUTH_CLIENT_SECRET
            INTERNAL_DISCORD_OAUTH_CLIENT_ID
            SECRET_DISCORD_OAUTH_CLIENT_SECRET
        env:
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_TEST }}
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_TEST }}
          APIKEY_ALCHEMY_PUBLIC: ${{ secrets.APIKEY_ALCHEMY_PUBLIC_GOERLI }}
          INTERNAL_GOOGLE_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_GOOGLE_OAUTH_CLIENT_ID_TEST }}
          SECRET_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_GOOGLE_OAUTH_CLIENT_SECRET_TEST }}
          INTERNAL_GITHUB_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_GITHUB_OAUTH_CLIENT_ID_TEST }}
          SECRET_GITHUB_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_GITHUB_OAUTH_CLIENT_SECRET_TEST }}
          INTERNAL_TWITTER_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_TWITTER_OAUTH_CLIENT_ID_TEST }}
          SECRET_TWITTER_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_TWITTER_OAUTH_CLIENT_SECRET_TEST }}
          INTERNAL_MICROSOFT_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_MICROSOFT_OAUTH_CLIENT_ID_TEST }}
          SECRET_MICROSOFT_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_MICROSOFT_OAUTH_CLIENT_SECRET_TEST }}
          INTERNAL_APPLE_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_APPLE_OAUTH_CLIENT_ID_TEST }}
          SECRET_APPLE_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_APPLE_OAUTH_CLIENT_SECRET_TEST }}
          INTERNAL_DISCORD_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_DISCORD_OAUTH_CLIENT_ID_TEST }}
          SECRET_DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_DISCORD_OAUTH_CLIENT_SECRET_TEST }}
