name: oort mono worker mainnet

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: oort/packages/mono

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: oort/.nvmrc
          cache: 'npm'
          cache-dependency-path: oort/package-lock.json
      - run: npm ci
      - run: npm run wrangler:publish:mainnet
        env:
          SITE: oort-mainnet
          ENVIRONMENT: production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          ENS_CONTRACT_ADDRESS: ${{ secrets.ENS_CONTRACT_ADDRESS_MAINNET }}
          ALCHEMY_API_URL: ${{ secrets.ALCHEMY_API_URL_MAINNET }}
          ALCHEMY_NFT_API_URL: ${{ secrets.ALCHEMY_NFT_API_URL_MAINNET }}
