---
name: Apps
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.changes.outputs.apps }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            apps: 'apps/**'

  build-test-apps:
    needs: changes
    if: needs.changes.outputs.apps == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            apps/node_modules
            apps/.yarn
          key: ${{ runner.os }}-apps-modules-${{ hashFiles('apps/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-apps-modules-

      - name: List the state of node modules
        continue-on-error: true
        run: npm list

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Install
        run: yarn install

      - name: Code Generation
        run: yarn gql

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
