---
name: Apps
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./apps

jobs:
  changes:
    runs-on: macos-latest
    outputs:
      apps: ${{ steps.changes.outputs.apps }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            apps:
              - 'apps/**'
              - '.github/workflows/pr-apps.yaml'

  build-test-apps:
    needs: changes
    if: needs.changes.outputs.apps == 'true'
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
