---
name: Packages
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./packages

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changes.outputs.packages }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            packages:
              - 'packages/**'
              - '.github/workflows/pr-packages.yaml'

  build-test-packages:
    needs: changes
    if: needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Restore node modules
        id: cache-node-modules-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Save node modules
        if: steps.cache-node-modules-restore.outputs.cache-hit != 'true'
        id: cache-node_modules-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ steps.cache-node-modules-restore.outputs.cache-primary-key }}

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
