---
name: Projects
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./projects

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.changes.outputs.projects }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            projects:
              - 'projects/**'
              - '.github/workflows/pr-projects.yaml'

  build-test-projects:
    needs: changes
    if: needs.changes.outputs.projects == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build projects.nix

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
