---
name: Platform
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./platform

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      platform: ${{ steps.changes.outputs.platform }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            platform:
              - 'platform/**'
              - '.github/workflows/pr-platform.yaml'

  build-test-platform:
    needs: changes
    if: needs.changes.outputs.platform == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - name: Restore node modules
        id: cache-node-modules-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Save node modules
        if: steps.cache-node-modules-restore.outputs.cache-hit != 'true'
        id: cache-node_modules-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ steps.cache-node-modules-restore.outputs.cache-primary-key }}

      - name: Code Generation
        run: yarn gql

      - name: Build
        run: yarn build
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.TOKEN_CLOUDFLARE_API }}
      - name: Test
        run: yarn test
