---
name: Packages
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./packages

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changes.outputs.packages }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            packages: 'packages/**'

  build-test-packages:
    needs: changes
    if: needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-packages-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-packages-modules-

      - name: List the state of node modules
        continue-on-error: true
        run: npm list

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build packages.nix

        # if: steps.cache-modules.outputs.cache-hit != 'true'
      # - uses: actions/setup-node@v3
      #   if: steps.cache-modules.outputs.cache-hit == 'true'
      #   with:
      #     node-version-file: .nvmrc
      #     cache: "yarn"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
