---
name: pr test and build
on:
  pull_request:
    branches:
      - main

jobs:
  build-test-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      # TODO: b/c files store at / this creates a permission denied at recovery
      # - name: Cache Nix
      #   id: cache-nix
      #   uses: actions/cache@v3
      #   with:
      #     path: /nix/store
      #     key: ${{ runner.os }}-nix

      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /tmp
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          retore-keys: |
            ${{ runner.os }}-modules-

      - name: List the state of node modules
        if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build

        # if: steps.cache-modules.outputs.cache-hit != 'true'
      # - uses: actions/setup-node@v3
      #   if: steps.cache-modules.outputs.cache-hit == 'true'
      #   with:
      #     node-version-file: .nvmrc
      #     cache: "yarn"

      - name: Install
        run: yarn install

      - name: Code Generation
        run: yarn gql

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
