---
name: test and build
on:
  pull_request:
    branches:
      - main

env:
  # NFTAR
  CHAIN: "ethereum"
  CHAIN_ID: 5
  OORT_URL: oort-devnet.kubelt.com
  STORAGE_KEY: ${{ secrets.NFT_STORAGE_DEV }}
  WALLET_PRIVATE_KEY: ${{ secrets.MINT_PFP_TEST_OPERATOR_PRIVATE_KEY }} # TODO: this is a bad env name
  ALCHEMY_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_GOERLI_API_KEY }}
  ALCHEMY_NETWORK: "ETH_MAINNET"
  INVITE_CONTRACT_ADDRESS: ${{ secrets.INVITE_TEST_CONTRACT_ADDRESS }}
  PFP_CONTRACT_ADDRESS: ${{ secrets.MINT_PFP_TEST_CONTRACT_ADDRESS }}
  NFTAR_API_KEY: "test"
  # SMART CONTRACTS
  CRDT_ETHERSCAN_API_KEY: ${{ secrets.CRDT_ETHERSCAN_API_KEY }}
  CRDT_GOERLI_OWNER_PRIVATE: ${{ secrets.CRDT_GOERLI_OWNER_PRIVATE }}
  CRDT_GOERLI_OWNER_ADDRESS: ${{ secrets.CRDT_GOERLI_OWNER_ADDRESS }}
  CRDT_GOERLI_ALCHEMY_URL: ${{ secrets.CRDT_GOERLI_ALCHEMY_URL }}
  CRDT_MUMBAI_ALCHEMY_URL: ${{ secrets.CRDT_MUMBAI_ALCHEMY_URL }}
  CRDT_POLYGON_ALCHEMY_URL: ${{ secrets.CRDT_POLYGON_ALCHEMY_URL }}
  CRDT_ETHEREUM_ALCHEMY_URL: ${{ secrets.CRDT_ETHEREUM_ALCHEMY_URL }}

jobs:
  build-test-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      # TODO: b/c files store at / this creates a permission denied at recovery
      # - name: Cache Nix
      #   id: cache-nix
      #   uses: actions/cache@v3
      #   with:
      #     path: /nix/store
      #     key: ${{ runner.os }}-nix
      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules--${{ hashFiles('yarn.lock') }}
      - uses: cachix/install-nix-action@v18
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
      - uses: actions/setup-node@v3
        if: steps.cache-modules.outputs.cache-hit == 'true'
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install
      - name: Code Generation
        run: yarn gql
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
