---
name: test and build
on:
  pull_request:
    branches:
      - main

env:
  # NFTAR
  # TODO: fix naming of env vars
  CHAIN: "ethereum"
  CHAIN_ID: 5
  OORT_URL: oort-devnet.kubelt.com
  STORAGE_KEY: ${{ secrets.NFT_STORAGE_DEV }}
  WALLET_PRIVATE_KEY: ${{ secrets.MINT_PFP_TEST_OPERATOR_PRIVATE_KEY }} # TODO: this is a bad env name
  ALCHEMY_URL: ${{ secrets.ALCHEMY_GOERLI_API_URL }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_GOERLI_API_KEY }}
  ALCHEMY_NETWORK: "ETH_MAINNET"
  INVITE_CONTRACT_ADDRESS: ${{ secrets.INVITE_TEST_CONTRACT_ADDRESS }}
  PFP_CONTRACT_ADDRESS: ${{ secrets.MINT_PFP_TEST_CONTRACT_ADDRESS }}
  NFTAR_API_KEY: "test"
  # SMART CONTRACT CRDT
  CRDT_ETHERSCAN_API_KEY: ${{ secrets.CRDT_ETHERSCAN_API_KEY }}
  CRDT_GOERLI_OWNER_PRIVATE: ${{ secrets.CRDT_GOERLI_OWNER_PRIVATE }}
  CRDT_GOERLI_OWNER_ADDRESS: ${{ secrets.CRDT_GOERLI_OWNER_ADDRESS }}
  CRDT_GOERLI_ALCHEMY_URL: ${{ secrets.CRDT_GOERLI_ALCHEMY_URL }}
  CRDT_MUMBAI_ALCHEMY_URL: ${{ secrets.CRDT_MUMBAI_ALCHEMY_URL }}
  CRDT_POLYGON_ALCHEMY_URL: ${{ secrets.CRDT_POLYGON_ALCHEMY_URL }}
  CRDT_ETHEREUM_ALCHEMY_URL: ${{ secrets.CRDT_ETHEREUM_ALCHEMY_URL }}
  # SMART CONTRACT INVITE
  # TODO: fix naming of env vars
  ETHERSCAN: ${{ secrets.CRDT_ETHERSCAN_API_KEY }}
  NFT_STORAGE_KEY_TEST: ${{ secrets.NFT_STORAGE_DEV }}
  NFT_STORAGE_KEY_MAIN: ${{ secrets.NFT_STORAGE_MAIN }}
  NFTAR_API_TOKEN_TESTNET: ${{ secrets.NFTAR_TEST_AUTHORIZATION }}
  NFTAR_API_TOKEN_MAINNET: ${{ secrets.NFTAR_AUTHORIZATION }}
  # LOCALHOST_OWNER_PK:
  # LOCALHOST_OPERATOR_PK:
  GOERLI_OWNER_PK: ${{ secrets.ETH_GOERLI_PK }}
  GOERLI_OPERATOR_PK: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }}
  MAINNET_OWNER_PK: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }} # FIXME
  MAINNET_OPERATOR_PK: ${{ secrets.INVITE_OPERATOR_PRIVATE_KEY }}
  MUMBAI_OWNER_PK: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }} # FIXME
  MUMBAI_OPERATOR_PK: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }} # FIXME
  POLYGON_OWNER_PK: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }} # FIXME
  POLYGON_OPERATOR_PK: ${{ secrets.INVITE_OPERATOR_TEST_PRIVATE_KEY }} # FIXME

jobs:
  build-test-workspace:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      # TODO: b/c files store at / this creates a permission denied at recovery
      # - name: Cache Nix
      #   id: cache-nix
      #   uses: actions/cache@v3
      #   with:
      #     path: /nix/store
      #     key: ${{ runner.os }}-nix

      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /tmp
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          retore-keys: |
            ${{ runner.os }}-modules-

      - name: List the state of node modules
        if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build

        # if: steps.cache-modules.outputs.cache-hit != 'true'
      # - uses: actions/setup-node@v3
      #   if: steps.cache-modules.outputs.cache-hit == 'true'
      #   with:
      #     node-version-file: .nvmrc
      #     cache: "yarn"

      - name: Install
        run: yarn install

      - name: Code Generation
        run: yarn gql

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
