---
name: pr test and build projects
on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.changes.outputs.projects }}
      packages: ${{ steps.changes.outputs.packages }}
    steps:
      # find out what deploy stack to use
      - uses: actions/checkout@master
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            projects: 'projects/**'
            packages: 'packages/**'

  build-test-workspace:
    needs: changes
    if: needs.changes.outputs.projects == 'true' || needs.changes.outputs.packages == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      # TODO: b/c files store at / this creates a permission denied at recovery
      # - name: Cache Nix
      #   id: cache-nix
      #   uses: actions/cache@v3
      #   with:
      #     path: /nix/store
      #     key: ${{ runner.os }}-nix

      - name: Cache Modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /tmp
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          retore-keys: |
            ${{ runner.os }}-modules-

      - name: List the state of node modules
        continue-on-error: true
        run: npm list

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build

        # if: steps.cache-modules.outputs.cache-hit != 'true'
      # - uses: actions/setup-node@v3
      #   if: steps.cache-modules.outputs.cache-hit == 'true'
      #   with:
      #     node-version-file: .nvmrc
      #     cache: "yarn"

      - name: Install
        run: yarn install --immutable

      - name: Code Generation
        run: yarn gql

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
