---
name: Release 3ID
on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-threeid-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Install
        run: yarn workspaces focus -A

      - name: Code Generation
        run: yarn gql

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/threeid'
          environment: 'current'
          command: publish --env current
          secrets: |
            TEST_ENV
            SESSION_SECRET
            DATADOG_CLIENT_TOKEN
            DATADOG_APPLICATION_ID
            DATADOG_ENV
            DATADOG_SERVICE_NAME
            OORT_HOST
            OORT_SCHEMA
            OORT_PORT
            NFTAR_URL
            NFTAR_AUTHORIZATION
            MINTPFP_CONTRACT_ADDRESS
            NFTAR_CHAIN_ID
            VALID_CHAIN_ID_NAME
            ALCHEMY_PUBLIC_API_KEY
            ALCHEMY_NFT_API_URL
        env:
          TEST_ENV: ''
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          # The Datadog client token.
          DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          DATADOG_APPLICATION_ID: ${{ secrets.DATADOG_APPLICATION_ID }}
          DATADOG_ENV: current
          DATADOG_SERVICE_NAME: 3id-application
          # The Cloudflare API token used by wrangler.
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          OORT_HOST: oort-mainnet.kubelt.com
          OORT_SCHEMA: https
          OORT_PORT: 443
          NFTAR_URL: ${{ secrets.NFTAR_URL }}
          NFTAR_AUTHORIZATION: ${{ secrets.NFTAR_AUTHORIZATION }}
          MINTPFP_CONTRACT_ADDRESS: ${{ secrets.MINTPFP_CONTRACT_ADDRESS }}
          NFTAR_CHAIN_ID: 1
          VALID_CHAIN_ID_NAME: mainnet
          ALCHEMY_PUBLIC_API_KEY: ${{ secrets.ALCHEMY_PUBLIC_API_KEY }}
          ALCHEMY_NFT_API_URL: ${{ secrets.ALCHEMY_NFT_API_URL }}
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      #   working-directory: threeid
      # - name: Run Playwright tests
      #   run: npx playwright test
      #   env:
      #     NODE_ENV: production
      #     ETH_GOERLI_PK: ${{ secrets.ETH_GOERLI_PK }} # TODO: setup prod pk
      #     DAPP_HOST: 3id.kubelt.com
      #     DAPP_PORT: 443
      #     DAPP_SCHEMA: https
      #   working-directory: threeid
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 5
