---
name: Release Passport
on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-passport-current:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          wranglerVersion: '3.19.0'
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/passport'
          command: publish --config wrangler.current.toml --env current
          environment: 'current'
          secrets: |
            SECRET_SESSION_KEY
            SECRET_SESSION_SALT
            SECRET_WEBAUTHN_SIGNING_KEY
            APIKEY_ALCHEMY_PUBLIC
            INTERNAL_GOOGLE_OAUTH_CLIENT_ID
            SECRET_GOOGLE_OAUTH_CLIENT_SECRET
            INTERNAL_GITHUB_OAUTH_CLIENT_ID
            SECRET_GITHUB_OAUTH_CLIENT_SECRET
            INTERNAL_TWITTER_OAUTH_CLIENT_ID
            SECRET_TWITTER_OAUTH_CLIENT_SECRET
            INTERNAL_MICROSOFT_OAUTH_CLIENT_ID
            SECRET_MICROSOFT_OAUTH_CLIENT_SECRET
            INTERNAL_APPLE_OAUTH_CLIENT_ID
            SECRET_APPLE_OAUTH_CLIENT_SECRET
            INTERNAL_DISCORD_OAUTH_CLIENT_ID
            SECRET_DISCORD_OAUTH_CLIENT_SECRET
        env:
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_PROD }}
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_PROD }}
          SECRET_WEBAUTHN_SIGNING_KEY: ${{ secrets.SECRET_WEBAUTHN_SIGNING_KEY_PROD }}
          APIKEY_ALCHEMY_PUBLIC: ${{ secrets.APIKEY_ALCHEMY_PUBLIC_MAINNET }}
          INTERNAL_GOOGLE_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_GOOGLE_OAUTH_CLIENT_ID_PROD }}
          SECRET_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_GOOGLE_OAUTH_CLIENT_SECRET_PROD }}
          INTERNAL_GITHUB_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_GITHUB_OAUTH_CLIENT_ID_PROD }}
          SECRET_GITHUB_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_GITHUB_OAUTH_CLIENT_SECRET_PROD }}
          INTERNAL_TWITTER_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_TWITTER_OAUTH_CLIENT_ID_PROD }}
          SECRET_TWITTER_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_TWITTER_OAUTH_CLIENT_SECRET_PROD }}
          INTERNAL_MICROSOFT_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_MICROSOFT_OAUTH_CLIENT_ID_PROD }}
          SECRET_MICROSOFT_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_MICROSOFT_OAUTH_CLIENT_SECRET_PROD }}
          INTERNAL_APPLE_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_APPLE_OAUTH_CLIENT_ID_PROD }}
          SECRET_APPLE_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_APPLE_OAUTH_CLIENT_SECRET_PROD }}
          INTERNAL_DISCORD_OAUTH_CLIENT_ID: ${{ vars.INTERNAL_DISCORD_OAUTH_CLIENT_ID_PROD }}
          SECRET_DISCORD_OAUTH_CLIENT_SECRET: ${{ secrets.SECRET_DISCORD_OAUTH_CLIENT_SECRET_PROD }}
