name: Release Oort

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Install
        run: yarn workspaces focus -A

      - name: Deploy Oort to Test Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "platform/oort"
          command: publish --env mainnet
          environment: "mainnet"
          secrets: |
            SITE
            ENVIRONMENT
            CLOUDFLARE_API_TOKEN
            CLOUDFLARE_ACCOUNT_ID
            DATADOG_API_KEY
            DATADOG_APP_KEY
            ENS_CONTRACT_ADDRESS
            ALCHEMY_API_URL
            ALCHEMY_NFT_API_URL
        env:
          SITE: oort-mainnet
          ENVIRONMENT: production
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          DATADOG_API_KEY: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APPLICATION_ID }}
          ENS_CONTRACT_ADDRESS: ${{ secrets.ENS_CONTRACT_ADDRESS }}
          ALCHEMY_API_URL: ${{ secrets.ALCHEMY_MAINNET_API_URL }}
          ALCHEMY_NFT_API_URL: ${{ secrets.ALCHEMY_MAINNET_API_URL }}
