---
name: Release Profile
on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-profile-current:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          wranglerVersion: '3.2.0'
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/profile'
          command: publish --config wrangler.current.toml --env current
          environment: 'current'
          secrets: |
            SECRET_SESSION_KEY
            SECRET_SESSION_SALT
            PROFILE_CLIENT_ID
            PROFILE_CLIENT_SECRET
            APIKEY_ALCHEMY_ETH
            APIKEY_ALCHEMY_POLYGON
        env:
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_PROD }}
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_PROD }}
          PROFILE_CLIENT_ID: ${{ vars.INTERNAL_PROFILE_OAUTH_CLIENT_ID_CURRENT }}
          PROFILE_CLIENT_SECRET: ${{ secrets.SECRET_PROFILE_OAUTH_CLIENT_SECRET_CURRENT }}
          APIKEY_ALCHEMY_ETH: ${{ secrets.APIKEY_ALCHEMY_GALAXY_MAINNET }}
          APIKEY_ALCHEMY_POLYGON: ${{ secrets.APIKEY_ALCHEMY_POLYGON_MAINNET }}
