---
name: Release Passport
on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-passport-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Code Generation
        run: yarn gql

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/passport'
          environment: 'current'
          command: publish --env current
          secrets: |
            SECRET_SESSION_SALT
            APIKEY_ALCHEMY_PUBLIC
        env:
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT }}
          APIKEY_ALCHEMY_PUBLIC: ${{ secrets.APIKEY_ALCHEMY_PUBLIC_MAINNET }}
