# .github/workflows/release-console.yaml
---
name: Release Console

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-console-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Deploy to Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/console'
          command: publish --env current
          environment: 'current'
          secrets: |
            SECRET_SESSION_KEY
        env:
          # A secret used for session encryption.
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_PROD }}
