name: Release Email

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: platform/email

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build ../platform.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn run test

      - name: Deploy
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: platform/email
          command: publish --env current
          environment: current
          secrets: |
            INTERNAL_DKIM_DOMAIN
            INTERNAL_DKIM_SELECTOR
            KEY_DKIM_PRIVATEKEY
        env:
          INTERNAL_DKIM_DOMAIN: ${{ secrets.INTERNAL_DKIM_DOMAIN }}
          INTERNAL_DKIM_SELECTOR: ${{ secrets.INTERNAL_DKIM_SELECTOR }}
          KEY_DKIM_PRIVATEKEY: ${{ secrets.KEY_DKIM_PRIVATEKEY }}
